### ISSUE TITLE
perf test failures due to slave service on OSX

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#10]
A lot of new test failures on the [OS X debug nightly](http://ci.ros2.org/view/nightly/job/nightly_osx_debug/429), most seem time-related:
```
Test Result (32 failures / +32)
projectroot.rclpytests
projectroot.gtest_spin__rmw_connext_cpp
projectroot.gtest_timer__rmw_connext_cpp
projectroot.gtest_timeout_subscriber__rmw_connext_cpp
projectroot.gtest_local_parameters__rmw_connext_cpp
projectroot.gtest_spin__rmw_fastrtps_cpp
projectroot.gtest_timer__rmw_fastrtps_cpp
projectroot.gtest_timeout_subscriber__rmw_fastrtps_cpp
projectroot.test_rate
projectroot.test_wait__rmw_connext_cpp
projectroot.test_wait__rmw_fastrtps_cpp
test_spin__rmw_connext_cpp.spin_until_future_complete_timeout
test_spin__rmw_connext_cpp.spin_until_future_complete_interrupted
test_spin__rmw_fastrtps_cpp.spin_until_future_complete_timeout
test_spin__rmw_fastrtps_cpp.spin_until_future_complete_interrupted
test_timeout_subscriber__rmw_connext_cpp.timeout_subscriber
TestRate.rate_basics
TestRate.wall_rate_basics
test_timeout_subscriber__rmw_fastrtps_cpp.timeout_subscriber
test_rclcpp.gtest_local_parameters__rmw_connext_cpp.gtest.missing_result
test_time__rmw_connext_cpp.timer_fire_regularly
WaitSetTestFixture__rmw_connext_cpp.finite_timeout
WaitSetTestFixture__rmw_connext_cpp.negative_timeout
WaitSetTestFixture__rmw_connext_cpp.canceled_timer
test_time__rmw_fastrtps_cpp.timer_fire_regularly
WaitSetTestFixture__rmw_fastrtps_cpp.finite_timeout
WaitSetTestFixture__rmw_fastrtps_cpp.negative_timeout
WaitSetTestFixture__rmw_fastrtps_cpp.canceled_timer
test.test_timer.test_timer_zero_callbacks1000hertz
test.test_timer.test_timer_number_callbacks100hertz
test.test_timer.test_timer_cancel_reset_10hertz
test.test_timer.test_timer_cancel_reset_1000hertz
```

there are new failures on [the repeated osx job](http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/659/#showFailuresLink) so this might not just be debug-related.
they didn't fail on the [nightly osx release job](http://ci.ros2.org/view/nightly/job/nightly_osx_release/427/) so it might be the configuration of mini1 & mini2 are different to dosa at the moment.

**Comment by dhood** [comment]
These are the changes that may have influenced this:
https://github.com/search?utf8=%E2%9C%93&q=user%3Aament+user%3Aros2+merged%3A%222017-04-17T22%3A00%3A00-08%3A00+..+2017-04-18T23%3A30%3A00-08%3A00%22&type=Issues

https://github.com/ros2/rcl/pull/124 is looking like the prime suspect since it's time-related, but there have also been changes to mini1 and mini2 yesterday ("Created launchd service from run_jenkins_slave.sh to supervise process and restart when needed.") that didn't make it onto dosa.

**Comment by dhood** [comment]
this is showing up in CI jobs too so it's definitely not debug related: http://ci.ros2.org/job/ci_osx/1943/#showFailuresLink

**Comment by wjwwood** [comment]
ros2/rcl#124 hopefully shouldn't affect it, since it only changed how the code was compiled, but didn't change it functionally. Let me know if I can help.

**Comment by dhood** [comment]
this looks to be specific to the machine. [Dosa is immune](http://ci.ros2.org/job/test_nightly_osx_debug/2/). [Confirmed that reverting ros2/rcl#124 doesn't fix it.](http://ci.ros2.org/view/All/job/test_nightly_osx_debug/3)

things went downhill for mini2 sometime between [this job, Apr 18, 2017 7:30:00 AM UTC (12:30 am PT)](http://ci.ros2.org/job/nightly_osx_release/426/) and [this job, Apr 18, 2017 9:25:12 PM UTC (2:25pm PT)](http://ci.ros2.org/job/ci_osx/1935/).

During that time "Created launchd service from run_jenkins_slave.sh to supervise process and restart when needed." was done so that's the new suspect.

**Comment by dhood** [comment]
I've unloaded the launchd service on mini2 and started [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1947)](http://ci.ros2.org/job/ci_osx/1947/) to check if it has an impact. :hourglass_flowing_sand:

**Comment by dhood** [comment]
CI is green for mini2 with the service unloaded. Doing the same for mini1: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1951)](http://ci.ros2.org/job/ci_osx/1951/)

**Comment by dhood** [comment]
@nuclearsandwich do you have any ideas for how to find a compromise here?

**Comment by dhood** [comment]
Some more context: the affected tests compare time taken for something to happen with an acceptable time. The time being taken is increased when the service is running.

Here's an example of a test that is supposed to take 10ms, and we allow 16ms:
https://github.com/ros2/rcl/blob/90176d9f1a3551deb861e698f36f81534e7763ac/rcl/test/rcl/test_wait.cpp#L191..L199. But, [it's taking 32ms](http://ci.ros2.org/view/nightly/job/nightly_osx_debug/429/testReport/junit/(root)/WaitSetTestFixture__rmw_connext_cpp/canceled_timer/)

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich do you have any ideas for how to find a compromise here?

Nothing off the top of my head. I expect that there's some default resource limits being applied that I wasn't aware of. I think unloading the managed services and going back to starting them manually until we can investigate is the way to go, and I'll try to look into it next week.

**Comment by dhood** [comment]
ok! to clarify: that is where we're at at the moment (unloaded on both machines for now) :+1:

**Comment by dhood** [comment]
I tried switching mini2 to use [this plist](https://gist.github.com/dhood/86202c739c3fa457b7f02321786c6331) that instead runs the script every five minutes, hoping that would use fewer resources, but that also made the tests fail. Unloaded it again.

**Comment by wjwwood** [comment]
mini2 seems to have this issue again:

[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2028)](http://ci.ros2.org/job/ci_osx/2028/)

**Comment by wjwwood** [comment]
I've launched identical jobs on the other machines for comparison:

- dosa: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2030)](http://ci.ros2.org/job/ci_osx/2030/)
- mini1: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2029)](http://ci.ros2.org/job/ci_osx/2029/)

**Comment by dhood** [comment]
I restarted mini2 today. It would have re-loaded it automatically; I've removed the plist from the directory on mini1 and mini2 so this doesn't happen accidentally again.

- mini2: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2031)](http://ci.ros2.org/job/ci_osx/2031/)

**Comment by mikaelarguedas** [comment]
Dosa has been running the jenkins agent as a service for a week now and didnt have to be reconnected manually a single time.

The build time of dosa seems to be more or less the same as the other machines.
Build time dosa: http://ci.ros2.org/job/ci_osx/3112/
Build time mini2: http://ci.ros2.org/job/ci_osx/3113/

In the last few weeks dosa doesnt seem to have fail any performance tests.
I'm going to reenable dosa for the nightly jobs and we could look into putting the other MacOS nodes under supervision as well

@dhood @nuclearsandwich FYI

**Comment by nuclearsandwich** [comment]
The secret sauce seemed to be convincing MacOS that the jenkins agent was a program that affects user interactivity (and I made it not very nice at all `-20` for good measure). If we do want to update the other two nodes, I'll probably commit the launchd plist to this repo or CI so that's versioned somewhere.

**Comment by nuclearsandwich** [comment]
The performance issues were resolved by the changes that are documented in https://github.com/ros2/ci/pull/118
