### ISSUE TITLE
pip failing on icecube

### ISSUE THREAD

**Issue by tfoote** [ros2/build_farmer#100]
Icecube has failed all builds inthe last couple of days. I've marked it offline to prevent more failures.

https://ci.ros2.org/computer/windows_icecube-f0532dcd/builds

The last two builds I checked are due to failing to invoke pip freeze with this traceback related to urllib3. 
```
10:25:02 ==> C:\Python36\python.exe -m pip freeze
10:25:02 Traceback (most recent call last):
10:25:02   File "C:\Python36\lib\runpy.py", line 183, in _run_module_as_main
10:25:02     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
10:25:02   File "C:\Python36\lib\runpy.py", line 142, in _get_module_details
10:25:02     return _get_module_details(pkg_main_name, error)
10:25:02   File "C:\Python36\lib\runpy.py", line 109, in _get_module_details
10:25:02     __import__(pkg_name)
10:25:02   File "C:\Python36\lib\site-packages\pip\__init__.py", line 21, in <module>
10:25:02     from pip._vendor.urllib3.exceptions import DependencyWarning
10:25:02 ModuleNotFoundError: No module named 'pip._vendor.urllib3'
10:25:02 <== 'C:\Python36\python.exe -m pip freeze' exited with return code '1'
```

![image](https://user-images.githubusercontent.com/447804/37632364-0f05652a-2bab-11e8-934f-98db6f8c7580.png)

**Comment by dhood** [comment]
yeah, the nightlies were failing for other reasons over the weekend so this was hard to spot. Thanks for taking it offline

**Comment by dhood** [comment]
back online: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4220)](https://ci.ros2.org/job/ci_windows/4220/). ran `python3 -m ensurepip --upgrade`
