### ISSUE TITLE
Flaky: multithreaded comms tests hanging with connext on osx

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#103]
This is the first time I've seen this: https://ci.ros2.org/job/nightly_osx_repeated/1045/testReport/junit/(root)/projectroot/gtest_multithreaded__rmw_connext_cpp/

[That test uses](https://github.com/ros2/system_tests/blob/0892acbedb6417d43b187e0685141188f9b282b1/test_rclcpp/test/test_multithreaded.cpp#L285_) a `wait_for_subscriber` call that underneath is [waiting for graph changes](https://github.com/ros2/system_tests/blob/acd4aec52f491f6a30c3b14a715c487f117197b5/test_rclcpp/include/test_rclcpp/utils.hpp#L57) so there's a chance this is caused by the same thing as https://github.com/ros2/rmw_connext/issues/280.

**Comment by dhood** [comment]
Don't think it's caused by the `wait_for_subscriber` call because (1) on another build a different one of those tests hung _after_ the `wait_for_subscriber` call: https://ci.ros2.org/job/ci_osx/3436/testReport/junit/(root)/projectroot/gtest_multithreaded__rmw_connext_cpp/ and (2) the implementation of `wait_for_subscriber` shouldn't hang because there's a low timeout being used.

**Comment by clalancette** [comment]
We haven't seen this in a while (over a week), so I'm going to close this out for now.  If it pops back up we can reopen.
