### ISSUE TITLE
colcon installed on windows machines

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#105]
@dirk-thomas could you please remove colcon from any machines you installed it on for testing? (AFAIU we don't want it installed by default at the moment)
e.g. portable has it installed https://ci.ros2.org/job/ci_windows/4268/consoleFull

**Comment by dirk-thomas** [comment]
I could uninstall the package but any time a build is being run with the `colcon` branch of the CI repo the packages are being installed since we don't use a build specific virtual env on Windows. What is the problem with them being installed but not being used?

**Comment by dhood** [comment]
I didn't realise we never use virtual environments on windows! My thinking was that it might accidentally mess with things (this is true for any non-default package), and not knowing that it's installed would mean that we overlook it/other "stealth" packages as potential causes of any unexpected behaviour. If we never use virtual environments then I see your point that it will just keep getting installed, so for now it  probably makes more sense to highlight its stealth status :)

I'll use this ticket to track that it is installed on (some?) windows machines

**Comment by clalancette** [comment]
@dhood @dirk-thomas colcon is intentionally installed on the Windows machines now, so I'm going to close this.  Feel free to re-open if I made a mistake.
