### ISSUE TITLE
Build farmer handoff 2018-04-04

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#107]
cc @nuclearsandwich 

- Expected test failures:
  - ~~Composition tests failing consistently on arm and debug, and some release~~ #86
      - eProsima has a fix and hopefully will release it soon so our nightlies go back to stable. at that point we should let the team know these test failures are not expected anymore.
- Flakiness:
  - service/parameter tests with fastrtps (common, shows as test failures or timeouts)
  - service/parameter tests with connext (less common, shows as a timeout) https://github.com/ros2/rmw_connext/issues/280
  - muiltithreaded tests hanging with connext https://github.com/ros2/build_cop/issues/103
  - pendulum_teleop hanging (only runs on connext, linux) https://github.com/ros2/build_cop/issues/94
      - should be less flaky after https://github.com/ros2/demos/pull/232
  - hanging tests with fastrtps https://github.com/ros2/build_cop/issues/98
     - TestFindWeakNodes, test_time_source, test_spin
  -  `DomainParticipantFactory_impl::create_participant():!create failure creating participant` failures on connext (seems can happen in any test): https://github.com/ros2/build_cop/issues/93
      - We should keep investigating/pushing on them for what is causing this now
  - test_utilities access violation: https://github.com/ros2/rclcpp/issues/458
  - "performance" tests (action pending discussion in https://github.com/ros2/rclcpp/issues/457)
    - e.g. `rclcpp.TestNode.now`, timer/waitset testing

- Buildfarmer tasks
  - reinstall mini3 (@dhood)
  - deploy https://github.com/ros2/ci/pull/141
  - keep an eye on https://github.com/ros2/build_cop/issues/106 and resolve if needed
  - Switch to VS2017 once Connext provides public binaries (ros2/ci#122)
  - Configure eatable as ros2 node when appropriate, also https://github.com/ros2/build_cop/issues/51

- Things to know
  - colcon python packages installed on (some?) windows machines https://github.com/ros2/build_cop/issues/105 (not necessarily an issue but should be kept in mind)
  - `flake8-builtins` is pinned and un-pinning is pending discussion in https://github.com/ros2/build_cop/issues/104
  - I deployed https://github.com/ros2/ci/pull/142 and https://github.com/ros2/ci/pull/133 yesterday (no issues so far)

**Comment by dhood** [comment]
forgot to mention rcl's get_node_names is also flaky and failures look like this: https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/775/testReport/junit/(root)/projectroot/test_get_node_names__rmw_fastrtps_cpp/

**Comment by dhood** [comment]
@nuclearsandwich asked what tools I used last stint to diagnose things as build cop. Mostly it's just being familiar with expected failures so you can spot things out of the ordinary (hence the detailed handoff) but I also found the following useful and added it to [the buildcop wiki](https://github.com/ros2/ros2/wiki/Build-Cop-and-Build-Farmer-Guide):

- To get the exact list of code that changed, generate a diff between the output of `vcs export --exact` between two builds.
  - This is particularly useful for external repos such as FastRTPS where old commits may get pushed to the master branch overnight, and are difficult to spot in the GitHub UI.
- If linter failures occur overnight it is usually because of a new version of a linter.
  - Create a diff of the last `pip freeze` output of two builds to see which versions changed.
  - If it's a regression in a dependency you can pin the older version temporarily, see [this PR for an example](https://github.com/ros2/ci/pull/129).

**Comment by nuclearsandwich** [comment]
Closing as I've handed off to mjcarroll in https://github.com/ros2/build_cop/issues/117
