### ISSUE TITLE
Agents delayed starting ssh-agent

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#108]
Build https://ci.ros2.org/job/packaging_osx/969 took 580 seconds to start the ssh-agent.

```
0.010  [ssh-agent] Looking for ssh-agent implementation...
580.867  [ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
```

A sample of the last few jobs on mini2 shows that this usually took between 0 and 2 seconds. The last two builds before 969 on mini2 took [10 seconds](https://ci.ros2.org/job/nightly_osx_debug/810/timestamps/?appendLog) and [530 seconds](https://ci.ros2.org/job/nightly_osx_repeated/1055/timestamps/?appendLog) leading up to the build so something may be a problem locally.

Recent builds on mini1 were fine (<1sec) with the exception of [this one](https://ci.ros2.org/job/nightly_osx_release/808/timestamps/?appendlog) which took 8 seconds.

At the moment I don't have any hypothesis and the issue may or may not be related to the recent network switching.

**Comment by nuclearsandwich** [comment]
Build https://ci.ros2.org/job/packaging_osx/971 mini2 failed the build when unable to start the ssh-agent after 15 minutes.

```
10:01:59 Building remotely on macos_mini2 (swarm macos) in workspace /Users/osrf/jenkins-agent/workspace/packaging_osx
10:01:59 [ssh-agent] Looking for ssh-agent implementation...
10:15:54 FATAL: [ssh-agent] Unable to start agent
```

**Comment by nuclearsandwich** [comment]
I had no trouble connecting to an ssh agent from a terminal session.I'm not terribly familiar with the ssh agent interface used by Jenkins but I may be digging into that next. The ssh-agent implementation appears to be the one which MacOS provides. I am not sure of its version relative to upstream openssh.

**Comment by nuclearsandwich** [comment]
This problem seems to be recurring but not consistent and there seem to be a handful of additional errors with mini2 that may be inter-related. Looking at this as part of a larger problem.

**Comment by dhood** [comment]
May or may not be ~~related~~ relevant but the osx node setup notes have this step (didn't do the second step on mini3 because it didn't have that directory, not sure what motivated it):
```
"install ssh-askpass via brew"
sudo ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin/ssh-askpass
```

**Comment by nuclearsandwich** [comment]
At this point I'm pretty sure that mini2 has issues beyond the ssh-agent delay. After a connection-loss based failure the next job run on mini2 has problems configuring its ssh agent, usually causing a second failure. It looks like the particular failure mode is leaving behind stale ssh-agent processes. While these are a potential credential leak they should be generally benign. However, clearing them with `killall ssh-agent` (only do this if the host isn't running a job or otherwise using any of the running ssh-agents). Allowed the next job to start the ssh-agent as swiftly as other nodes so there is some relationship between the dangling ssh-agent processes and ssh-agent initialization time.

Before `killall ssh-agent`:
```
mini2:~ osrf$ pgrep ssh-agent
1050
2735
18063
23308
24295
24987
25515
26980
28005
33172
43061
46922
46940
47848
54606
63270
68684
71701
72597
73783
75480
75490
81695
83822
84275
85467
88869
89221
91113
93605
93618
94223
94244
```

**Comment by nuclearsandwich** [comment]
This issue was caused by dangling ssh-agent processes staying open after #109. It's a possible manual cleanup step after any connection related job failure.

**Comment by nuclearsandwich** [comment]
As we recently saw an interrupted build on a linux host, we've also seen this issue affect other hosts so I've posthumously updated the issue title.
