### ISSUE TITLE
WaitSetTestFixture__rmw_connext_cpp/zero_timeout flaky on windows

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#11]
This has been flaky for a while but I saw it fail 10 times today so I figured I'll report it here.
It's this test: https://github.com/ros2/rcl/blob/90176d9f1a3551deb861e698f36f81534e7763ac/rcl/test/rcl/test_wait.cpp#L131

Failed on this ci; http://ci.ros2.org/job/ci_windows/2612/testReport/junit/(root)/WaitSetTestFixture__rmw_connext_cpp/zero_timeout/

Fails only on windows, it doesn't seem to be machine related AFAIK

**Comment by dhood** [comment]
to confirm: when you say "saw it fail 10 times" you mean that it didn't successfully pass even with `--retest-until-pass 10`, right? It's not that you saw this on multiple jobs

**Comment by mikaelarguedas** [comment]
you mean that it didn't successfully pass even with --retest-until-pass 10 << :+1:

**Comment by mikaelarguedas** [comment]
All windows timer /performance test failures are now tracked at https://github.com/ros2/rcl/issues/188 nd connected tickets
