### ISSUE TITLE
connext failing to communicate on mini1

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#110]
See the output of this test failure:

https://ci.ros2.org/job/ci_osx/3483/testReport/junit/(root)/projectroot/test_get_node_names__rmw_connext_cpp/

```
COMMENDSrWriterService_assertRemoteReader:Discovered remote reader with GUID 0XAC1801A3,0X22C1,0X6,0X3C7 using a non-addressable locator.
This can occur if the transport is not installed and/or enabled in the local participant.
See https://community.rti.com/kb/what-does-cant-reach-locator-error-message-mean for additional info.
can't reach: locator: shmem://0000:0006:0403:0000:0000:0000:0000:0000:17160
```

I didn't really have time to dig into the why, and it's not blocking me, but I thought I'd make an issue to track it.

**Comment by dhood** [comment]
I asked @rohitsalem to close the RTI Admin Consol which can cause outputs like this.

**Comment by nuclearsandwich** [comment]
When was the RTI admin console first left open? There was output like this on mini1 in one of the nightly tests https://ci.ros2.org/view/nightly/job/nightly_osx_release/820/testReport/junit/(root)/projectroot/test_get_node_names__rmw_connext_cpp/

The console does appear to be closed now (checking mini1 via VNC)

**Comment by rohitsalem** [comment]
Yes it was on since yesterday afternoon until @dhood told me :| my bad.

**Comment by mikaelarguedas** [comment]
But you were on the b network right ?

**Comment by dirk-thomas** [comment]
This build supports that the admin console was interfering with the Jenkins nodes: https://ci.ros2.org/job/ci_windows/4318/testReport/junit/(root)/projectroot/test_get_node_names__rmw_connext_cpp/

**Comment by nuclearsandwich** [comment]
I didn't see this output on any of the completed nightlies now that the admin console has been closed so I'm closing the issue.

**Comment by rohitsalem** [comment]
@mikaelarguedas Yes, at the start I was, but I forgot to shut down the console after I switched back to Network A.
