### ISSUE TITLE
Windows jobs failing with "input line is too long"

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#111]
It's been failing on the debug nightly for 2 days:
- https://ci.ros2.org/view/nightly/job/nightly_win_deb/850

And showed up during the day on a job testing all 3 DDS implementations:
- https://ci.ros2.org/job/ci_windows/4349/

**Comment by nuclearsandwich** [comment]
So I've verified that a shorter job name allows debug and release builds to pass but renaming the job seems like it would only kick the can down the road. Maybe kicking the can is enough to get us relying more on devel style jobs with colcon and less on the comprehensive builds that we're currently using.

Another option is to stop building Windows jobs with --isolated by default.

**Comment by dirk-thomas** [comment]
> Another option is to stop building Windows jobs with `--isolated` by default.

This sounds like an easy option. Since we still cover isolation on the other platforms we shouldn't miss anything slipping through because of that.

**Comment by mikaelarguedas** [comment]
> So I've verified that a shorter job name allows debug and release builds to pass 

Does this also make the jobs pass when the 3 RMW implementations are enabled?

**Comment by nuclearsandwich** [comment]
> Does this also make the jobs pass when the 3 RMW implementations are enabled?

I've so far only tested the Release and Debug job default configurations. Is the expectation that it will still fail when all three are enabled?

**Comment by mikaelarguedas** [comment]
https://ci.ros2.org/job/ci_windows/4349/ failed without a specific build type, so I think it's worth testing it with the job name change to make sure this is still under the limit as well

**Comment by nuclearsandwich** [comment]
Even with the job name `n_win_deb` a build with all three RMW implementations fails with isolation.

As a side note, I haven't been linking example jobs because I keep renaming the job in Jenkins with different lengths and Jenkins has no built in redirection for renamed jobs. We would set new rewrite rules in the proxy configuration.

**Comment by nuclearsandwich** [comment]
Opened https://github.com/ros2/ci/pull/152 to run the windows jobs with isolation disabled.

**Comment by nuclearsandwich** [comment]
Windows jobs now have isolation disabled by default. I'll check in on the nightlies tomorrow and close this issue if they are successful. One of the other mitigation options was switching to powershell for Windows jobs. @dirk-thomas I think you were the one who mentioned it. Is that something we want to pursue before bouncy and should track separately? Are there any existing issues that tie in with it?

**Comment by dirk-thomas** [comment]
Powershell support has already been implemented in `colcon`. It is only a matter of trying to use it in the Windows jobs. But let get `colcon` rolled out to CI first and then consider the next steps.

**Comment by nuclearsandwich** [comment]
I'm closing this now that https://github.com/ros2/ci/pull/152 is merged. Powershell migration can be a separate discussion.
