### ISSUE TITLE
Tests mistakenly reported as failing

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#112]
I have noticed some "regressions" that seem to have actually passed.

Examples:
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/395/testReport/junit/(root)/projectroot/gtest_rttest_api/
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/395/testReport/junit/(root)/projectroot/rviz_common_config_test/

https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1002/testReport/junit/(root)/projectroot/test_default_state_machine/

The build summary doesn't seem to think there's been an error:
```
build/rttest/test_results/rttest/gtest_rttest_api.gtest.xml: 6 tests, 0 errors, 0 failures, 0 skipped
...
build/rviz_common/test_results/rviz_common/rviz_common_config_test.gtest.xml: 3 tests, 0 errors, 0 failures, 0 skipped
```

@dirk-thomas @mikaelarguedas am I right in thinking this is a colcon issue? Or could the false positives come from jenkins somehow.

**Comment by nuclearsandwich** [comment]
> https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1002/testReport/junit/(root)/projectroot/test_default_state_machine/

I'm not sure what might have triggered a failure state in the first two but it's possible that the lines
```
[WARN] [rcl_lifecycle]: No callback transition matching 3 found for current state unconfigured
[ERROR] [rcl_lifecycle]: No transition found for node unconfigured with key 3
```

would have tripped the test reporter despite the fact that the test eventually passed. I don't see input matching that pattern in the previous few repeated linux nightlies.

**Comment by dhood** [comment]
As another data point, [this test is reported as failing for fastrtps](https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1002/testReport/junit/(root)/projectroot/test_tlsf__rmw_fastrtps_cpp/), when actually it only [failed for connext](https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1002/testReport/junit/(root)/projectroot/test_tlsf__rmw_connext_cpp/).

```
07:18:48.178 build/tlsf_cpp/test_results/tlsf_cpp/test_tlsf__rmw_connext_cpp.gtest.xml: 2 tests, 0 errors, 1 failure, 0 skipped
07:18:48.178 build/tlsf_cpp/test_results/tlsf_cpp/test_tlsf__rmw_fastrtps_cpp.gtest.xml: 2 tests, 0 errors, 0 failures, 0 skipped
```

**Comment by dirk-thomas** [comment]
> As another data point,

The output of the FastRTPS test doesn't look complete in Jenkins. It doesn't end with the usual three lines:

> -- run_test.py: return code X
> -- run_test.py: inject classname prefix into ...
> -- run_test.py: verify result file ...

**Comment by Karsten1987** [comment]
As for the lifecycle tests: That test seems to be correct, as it actively looks for unavailable transitions. However, an error message is printed when trying to call one of this unavailable transitions. Do you want me to change the tests for that?

**Comment by dirk-thomas** [comment]
colcon/colcon-core#25 will hopefully help to clarify what the return code of each invoked command is.

**Comment by dhood** [comment]
I didn't notice this after https://github.com/colcon/colcon-core/pull/25 but wasn't watching nigthlies too closely, did you @nuclearsandwich? or good to close?

**Comment by nuclearsandwich** [comment]
> did you @nuclearsandwich? or good to close?

I haven't seen it either. FYI @mjcarroll if you see failures like this you can re-open the issue.
