### ISSUE TITLE
Windows debug image_tools failure

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#113]
`image_tools` tests are timing out on windows debug (failing, not flaky). This is true for fastrtps and connext.

https://ci.ros2.org/view/nightly/job/nightly_win_deb/856/testReport/junit/(root)/projectroot/test_showimage_cam2image__rmw_connext_cpp/

This test relies on console output matching so something might be printed in a weird way that's preventing it from matching. I'm running https://ci.ros2.org/job/ci_windows/4365/ to see the failure output.

**Comment by dhood** [comment]
[conclusion from the test output](https://ci.ros2.org/job/ci_windows/4365/testReport/junit/(root)/projectroot/test_showimage_cam2image__rmw_connext_cpp/) is that it is an issue in the cam2image process caused by opencv.

```
[test_cam2image] OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file C:\dev\opencv_custom_build\opencv\modules\core\src\array.cpp, line 2482
```

We switched visual studio version lately, and I think we have a custom-built opencv version, so did we not rebuild it when we should have, perhaps?

**Comment by dirk-thomas** [comment]
I am pretty sure that the `vs14` (Visual Studio 2015) as well as `vs15` (Visual Studio 2017) "packages" of OpenCV are installed on all the build nodes. Could it be that these files are named incorrectly then and the `vs15` archive doesn't actually contains Visual Studio 15.0 aka 2017 binaries?

**Comment by mikaelarguedas** [comment]
The vs2017 archive doesn't contain the Debug libraries.
It looks like when this was built for vc15 it was built only in Release and not in Debug.

**Comment by nuclearsandwich** [comment]
I've been working on the solution for this the latter half of this week. Getting OpenCV 3.4.1 builds for vc15 (Visual Studio 2017) in Release and Debug configurations. I am not planning to build for vc14 (VS 2015) as I expect we are only supporting VS2017 from Bouncy on

**Comment by mikaelarguedas** [comment]
For additional context: we picked OpenCV 3.4.1 instead of 3.2.0 because it has CMake fixes we need to build on Visual Studio 2017, it happens to be the same version as on MacOS but that doesn't imply that we'll build new binaries when a new version comes out

**Comment by mikaelarguedas** [comment]
@nuclearsandwich tI think his can be closed now that we released the updated archives and that the nightlies are back to green

**Comment by nuclearsandwich** [comment]
Yes indeed we can.
