### ISSUE TITLE
Build Farmer Handoff 2018-05-09

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#117]
Incoming: @mjcarroll 
Outgoing: @nuclearsandwich

#### Expected failures:
  - CMake Warnings from https://github.com/ros2/build_cop/issues/79 have returned but are not ubiquitous https://github.com/ros2/ci/pull/166 is a proposed solution.

#### New flakiness:
  - composition test flakiness increase (to be investigated) https://github.com/ros2/build_cop/issues/118

#### Long-running flakiness:
  - service/parameter tests with fastrtps (common, shows as test failures or timeouts)
  - service/parameter tests with connext (less common, shows as a timeout) https://github.com/ros2/rmw_connext/issues/280
  - muiltithreaded tests hanging with connext https://github.com/ros2/build_cop/issues/103
  - pendulum_teleop hanging (only runs on connext, linux) https://github.com/ros2/build_cop/issues/94
      - should be less flaky after https://github.com/ros2/demos/pull/232
  - hanging tests with fastrtps https://github.com/ros2/build_cop/issues/98
     - TestFindWeakNodes, test_time_source, test_spin
  -  `DomainParticipantFactory_impl::create_participant():!create failure creating participant` failures on connext (seems can happen in any test): https://github.com/ros2/build_cop/issues/93
      - We should keep investigating/pushing on them for what is causing this now
  - ~test_utilities access violation~: https://github.com/ros2/rclcpp/issues/458
  - "performance" tests (action pending discussion in https://github.com/ros2/rclcpp/issues/457)
    - e.g. `rclcpp.TestNode.now`, timer/waitset testing
  - projectroot.test_dynamic_bridge__rmw_fastrtps_cpp / ros1_bridge.test_dynamic_bridge__rmw_fastrtps_cpp.xunit.missing_result (flaky due to fastrtps discovery issues)

#### Build farmer tasks

- Update Java to 1.8u162 on all hosts (including master): @nuclearsandwich
- Renew https certificate on ci.ros2.org: @nuclearsandwich
- Periodic upgrades on Mac and Windows: Build farmer
- Profile memory usage of bridge compilation job https://github.com/ros2/build_cop/issues/106 (failures currently resolved by increasing instance size)

**Comment by dhood** [comment]
I edited the original post to reference https://github.com/ros2/build_cop/issues/118 (commenting because notifications of edits don't get emailed)

**Comment by mjcarroll** [comment]
Closing for handoff to @dirk-thomas #119
