### ISSUE TITLE
Build Farmer Handoff 2018-05-23

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#119]
Incoming: @dirk-thomas  
Outgoing: @mjcarroll

#### Expected failures:
  - ~~CMake Warnings from https://github.com/ros2/build_cop/issues/79 have returned but are not ubiquitous https://github.com/ros2/ci/pull/166 is a proposed solution.~~

#### New flakiness:
  - rviz_common.selection_manager_test missing results on osx_nightly_repeated: https://github.com/ros2/rviz/issues/271 (seems to only affect macos)
  - composition test flakiness increase (to be investigated) https://github.com/ros2/build_cop/issues/118

#### Long-running flakiness:
  - service/parameter tests with fastrtps (common, shows as test failures or timeouts)
  - service/parameter tests with connext (less common, shows as a timeout) https://github.com/ros2/rmw_connext/issues/280
  - muiltithreaded tests hanging with connext https://github.com/ros2/build_cop/issues/103
  - pendulum_teleop hanging (only runs on connext, linux) https://github.com/ros2/build_cop/issues/94
      - should be less flaky after https://github.com/ros2/demos/pull/232
  - hanging tests with fastrtps https://github.com/ros2/build_cop/issues/98
     - TestFindWeakNodes, test_time_source, test_spin
  -  `DomainParticipantFactory_impl::create_participant():!create failure creating participant` failures on connext (seems can happen in any test): https://github.com/ros2/build_cop/issues/93
      - We should keep investigating/pushing on them for what is causing this now
  - ~test_utilities access violation~: https://github.com/ros2/rclcpp/issues/458
  - "performance" tests (action pending discussion in https://github.com/ros2/rclcpp/issues/457)
    - e.g. `rclcpp.TestNode.now`, timer/waitset testing
  - projectroot.test_dynamic_bridge__rmw_fastrtps_cpp / ros1_bridge.test_dynamic_bridge__rmw_fastrtps_cpp.xunit.missing_result (flaky due to fastrtps discovery issues)

#### Build farmer tasks

- Update Java to 1.8u162 on all hosts (including master): @nuclearsandwich
- [x] ~~Renew https certificate on ci.ros2.org: @nuclearsandwich~~
- Periodic upgrades on Mac and Windows: Build farmer
- Profile memory usage of bridge compilation job https://github.com/ros2/build_cop/issues/106 (failures currently resolved by increasing instance size)

**Comment by mjcarroll** [comment]
Rolling to you @dirk-thomas since @clalancette is busy with Melodic release and @mikaelarguedas is at a timezone disadvantage.

**Comment by dirk-thomas** [comment]
> Expected failures:
> CMake Warnings from #79 have returned but are not ubiquitous ros2/ci#166 is a proposed solution.

The patch has already been merged 8 days ago.

**Comment by mjcarroll** [comment]
Sorry, copy-paste error.
In that case, I would not expect it to fail.

**Comment by mikaelarguedas** [comment]
I saw one fail yesterday https://ci.ros2.org/view/nightly/job/nightly_linux_debug/841/   and opened  https://github.com/ros2/rviz/pull/273 to work around it

**Comment by dhood** [comment]
Timeouts are no longer expected for two-process client-service tests (e.g. `test_client_scope_cpp`, `test_client_scope_consistency_cpp`) with connext after https://github.com/ros2/rclcpp/pull/476. Please point out if they show up again.

However, some other timeouts still happen e.g. `test_tutorial_parameter_events__rmw_connext_cpp` (see https://github.com/ros2/build_cop/issues/118#issuecomment-391431017) or `test_remote_parameters[_async]`

**Comment by mikaelarguedas** [comment]
MacOS nodes should be updated to install poco from brew and test that this allows to build workspace and overlays without needing to build poco from source.

- brew install poco
- run a test ci job
- run a test packaging job
- build the examples repo on top of the packaging artifact
- run some examples from the overlay
- propagate to the other Mac machines
- update node setup instructions and wiki installation instructions accordingly

**Comment by dirk-thomas** [comment]
What else happened in the paste two weeks:
* The Connext Debian package was imported to our apt repos.
* A new parameter to use that Debian package was added to the job (ros2/ci#181).
* The new Visual Studio 2017 binaries of OpenSplice were installed on all three Windows executors (example build: https://ci.ros2.org/job/ci_windows/4642/).
* The packet machine went offline and only a restart of the master made it reconnect.
