### ISSUE TITLE
Connext no space left on device during pendulum demo on linux coverage job

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#12]
Pendulum demo tests on this [linux coverage job on linux3](http://ci.ros2.org/job/nightly_linux_coverage/355/#showFailuresLink) failed with a lot of connext errors.

Both test_pendulum_teleop__rmw_connext_cpp.test_executable and projectroot.test_pendulum__rmw_connext_cpp.test_pendulum__rmw_connext_cpp output the following warning multiple times:
```
[test_executable_0] [D0108|ENABLE]NDDS_Transport_Shmem_create_recvresource_rrEA:failed to initialize shared memory resource mutex for key 0xb086c2
[test_executable_0] [D0108|ENABLE]RTIOsapiSharedMemoryMutex_create:OS semget() failure, error 0X1C: No space left on device
```

before finally:
```
[test_executable_0] [D0108|ENABLE]DDS_DomainParticipantPresentation_reserve_participant_index_entryports:!enable reserve participant index
[test_executable_0] [D0108|ENABLE]DDS_DomainParticipant_enableI:Automatic participant index failed to initialize. PLEASE VERIFY CONSISTENT TRANSPORT / DISCOVERY CONFIGURATION. 
[test_executable_0] DDSDomainParticipant_impl::createI:ERROR: Failed to auto-enable entity
[test_executable_0] DomainParticipantFactory_impl::create_participant():!create failure creating participant
(test_executable_0) rc -6
[test_executable_1] [D0108|ENABLE]NDDS_Transport_Shmem_create_recvresource_rrEA:failed to initialize shared memory resource mutex for key 0xb08758
[test_executable_1] [D0108|ENABLE]DDS_DomainParticipantPresentation_reserve_participant_index_entryports:!enable reserve participant index
[test_executable_1] [D0108|ENABLE]DDS_DomainParticipant_enableI:Automatic participant index failed to initialize. PLEASE VERIFY CONSISTENT TRANSPORT / DISCOVERY CONFIGURATION. 
[test_executable_1] DDSDomainParticipant_impl::createI:ERROR: Failed to auto-enable entity
[test_executable_1] DomainParticipantFactory_impl::create_participant():!create failure creating participant
(test_executable_1) rc 250
```

**Comment by Karsten1987** [comment]
related issue: https://github.com/ros2/rmw_connext/issues/223

**Comment by dhood** [comment]
thanks, the job in that issue was also on linux 3 (most of the other comments are for OS X). I'll have to look into how to configure that increase in shared memory for our linux nodes.
I'm not sure what caused this to happen last night for the first time.. None of the changes from yesterday are standing out: https://github.com/search?p=2&q=user%3Aament+user%3Aros2+merged%3A%222017-04-19T22%3A00%3A00-08%3A00+..+2017-04-21T23%3A30%3A00-08%3A00%22&type=Issues&utf8=%E2%9C%93
Might have just been "luck"

**Comment by Karsten1987** [comment]
at least from my part, I constantly run into this problem whenever I test
the RTI connext namespace impl.

**Comment by dhood** [comment]
Ah great, thanks!

**Comment by dhood** [comment]
I'm using the `namespace_impl` branches to get this error to be output consistently.

Increasing the shared memory of the docker container to 1Gb using the following invocation does not address the issue:
```
docker run --privileged --shm-size=1G -e UID=`id -u` -e GID=`id -g` -e CI_ARGS="$CI_ARGS" -e CCACHE_DIR=/home/rosbuild/.ccache -i -v `pwd`:/home/rosbuild/ci_scripts -v $HOME/.ccache:/home/rosbuild/.ccache $CONTAINER_NAME
```

http://ci.ros2.org/job/test_ci_linux/2/

It resulted in the following `df -h` output from inside the container:
```
00:18:18 Filesystem      Size  Used Avail Use% Mounted on
00:18:18 none            985G  745G  200G  79% /
00:18:18 tmpfs           1.9G     0  1.9G   0% /dev
00:18:18 tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
00:18:18 /dev/xvda1      985G  745G  200G  79% /etc/hosts
00:18:18 shm             1.0G     0  1.0G   0% /dev/shm
```

but the errors persist:
```
[test_publisher] [D0108|ENABLE]NDDS_Transport_Shmem_create_recvresource_rrEA:failed to initialize shared memory resource mutex for key 0xb0870c
01:46:47 75: [test_publisher] [D0108|ENABLE]RTIOsapiSharedMemoryMutex_create:OS semget() failure, error 0X1C: No space left on device
```

**Comment by Karsten1987** [comment]
I am not sure if increasing only `/dev/shm` does suffice here. I don't know docker well enough, but is there any way of setting this config file before running the job?
Maybe just something like:
```
sudo echo kernel.sem = 250 32000 100 1024 > /etc/sysctl.conf
```

> Linux Systems
> Each RTI Connext application that has shared memory enabled allocates 2 individual semaphores. The Linux system defaults allow only 128 per host, which may not be enough (one is often used by the system, so you'll run out at the 64th domain/index combination). 
> 
> To increase the number of semaphores available to RTI Connext, change the values of semmns and semmni in /etc/sysctl.conf. The following values are just one possible example; they show semmns to be 32000 andsemmni to be 1024: 
> 
> \# semaphores: semmsl, semmns, semopm, semmni 
> kernel.sem = 250 32000 100 1024 
> If those parameters already exist in /etc/sysctl.conf, change their values; otherwise, add the lines to your /etc/sysctl.conf file.

**Comment by Karsten1987** [comment]
looks like I've got some results: http://ci.ros2.org/view/All/job/test_ci_linux/14/
The connext jobs still fail, but the original connext error of this PR does not occur anymore.

So basically the new docker configuration should look like this:
```
docker run --privileged --shm-size=1G --sysctl kernel.shmmax=1073741824 --sysctl kernel.shmmni=1024 --sysctl kernel.sem="250 32000 100 1024" ...
```

How do we proceed further with this?

**Comment by dhood** [comment]
@Karsten1987 I think you managed to get the namespace_impl PRs merged without any changes to the Dockerfile, right? Do you remember what the condition was that caused the error (and why those PRs didn't need it in the end)?

**Comment by Karsten1987** [comment]
Sorry, I've just seen this. It magically just worked. I can't really tell what changed in between.
With the configuration I mentioned above, the error definitely disappeared, so I believe it's valuable to have it for future references.

**Comment by dhood** [comment]
OK, thanks for the update. yeah, we're almost certainly going to run into this again at some point. Can you delete the test CI "project" on jenkins once you're completely done with it please? I'll close this issue out for now.
