### ISSUE TITLE
repeat-until-fail doesnt stop on failure for "pure pytest"

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#121]
Repeated nightly jobs:

Expected behavior:
------------------------
Repeat all passing test up to N times and stop repeating a test as soon as it fails once 

Actual behavior:
---------------------
Python packages with pytest tests like `ros2topic` have all tests repeated N times. So we can see on [this job](https://ci.ros2.org/view/All/job/nightly_osx_repeated/1121/consoleFull#console-section-568) that `ros2topic` has 5 tests, including one failing.
The end result is `11 failed, 44 passed in 19.38 seconds`, the failing test being repeated 10 times

cc @dirk-thomas as build cop

**Comment by dirk-thomas** [comment]
`pytest-repeat` will run each test N times. Afaik the only option to abort on the first failure would the `-x` option of `pytest` itself (https://pypi.org/project/pytest-repeat/#repeating-a-test-until-failure) which (I think) we don't want to use.

**Comment by dirk-thomas** [comment]
> ... which (I think) we don't want to use.

I just confirmed that this is how `-x` works in combination with `pytest-repeat`. If you have three tests A, B, C and repeat the tests 2 times you get the following sequence: A1, A2, A3, B1, B2, B3, C1, C2, C3.

In the case where B2 fails the processing stops right there and doesn't run B3 (as desired) or any of the C's (which we don't want).

**Comment by mikaelarguedas** [comment]
:( sad.

I guess we can document the change in https://github.com/colcon/colcon.readthedocs.org/blob/master/migration/ament_tools.rst and close this issue then

Thanks for investigating

**Comment by mikaelarguedas** [comment]
Documentation PR opened at https://github.com/colcon/colcon.readthedocs.org/pull/18

**Comment by mikaelarguedas** [comment]
Closing this as https://github.com/colcon/colcon.readthedocs.org/pull/18 has merged
