### ISSUE TITLE
Build Farmer Handoff 2018-06-06

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#122]
Incoming: @clalancette
Outgoing: @dirk-thomas from #119

#### Requests pending:
  - install poco from brew on macOS machines (see https://github.com/ros2/build_cop/issues/119#issuecomment-392772055)

#### Flakiness:
  - rviz_common.selection_manager_test missing results on osx_nightly_repeated: https://github.com/ros2/rviz/issues/271 (seems to only affect macos)
  - composition test flakiness increase (to be investigated) https://github.com/ros2/build_cop/issues/118
  - service/parameter tests with fastrtps (common, shows as test failures or timeouts)
  - multithreaded tests hanging with connext https://github.com/ros2/build_cop/issues/103
  - pendulum_teleop hanging (only runs on connext, linux) https://github.com/ros2/build_cop/issues/94
      - should be less flaky after https://github.com/ros2/demos/pull/232
  - hanging tests with fastrtps https://github.com/ros2/build_cop/issues/98
     - TestFindWeakNodes, test_time_source, test_spin
  -  `DomainParticipantFactory_impl::create_participant():!create failure creating participant` failures on connext (seems can happen in any test): https://github.com/ros2/build_cop/issues/93
      - We should keep investigating/pushing on them for what is causing this now
  - "performance" tests (action pending discussion in https://github.com/ros2/rclcpp/issues/457)
    - e.g. `rclcpp.TestNode.now`, timer/waitset testing
  - projectroot.test_dynamic_bridge__rmw_fastrtps_cpp / ros1_bridge.test_dynamic_bridge__rmw_fastrtps_cpp.xunit.missing_result (flaky due to fastrtps discovery issues)

#### Build farmer tasks

- Update Java to 1.8u162 on all hosts (including master): @nuclearsandwich
- Periodic upgrades on Mac and Windows: Build farmer
- Profile memory usage of bridge compilation job https://github.com/ros2/build_cop/issues/106 (failures currently resolved by increasing instance size)

**Comment by mikaelarguedas** [comment]
In the last round, we also started testing OpenSplice again and it shows some flaky tests with pretty high failure rate: e.g. https://ci.ros2.org/view/nightly/job/nightly_linux_ospl_release/7/testReport/

**Comment by nuclearsandwich** [comment]
> Incoming: @dirk-thomas from #119
> Outgoing: @clalancette

Are incoming and outgoing reversed here?

**Comment by clalancette** [comment]
> Are incoming and outgoing reversed here?

Yes, I'm the incoming one.  I'll fix it up.

**Comment by clalancette** [comment]
I installed system updates on all MacOS and Windows nodes today.  I also ended up testing and then installing poco from brew on the MacOS nodes (assimp was already installed on all nodes).

**Comment by mikaelarguedas** [comment]
thanks! updated the release checklist ticket accordingly

**Comment by mikaelarguedas** [comment]
Referencing it here so that next time we update the macOS nodes we keep it in mind.
brew now shipe python3.7 and some of our pip dependencies don't compile against the new python version https://github.com/ros2/ros2/issues/522

**Comment by clalancette** [comment]
Handed off to the new buildfarmer in #140, so closing.
