### ISSUE TITLE
mini2 very slow

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#124]
Since ~24hours, mini2 is taking >3hours just for the build step of ros2.repos:
This shows up on nightlies and on regular CI
https://ci.ros2.org/job/nightly_osx_debug/885: `Summary: 173 packages finished [11264.54s]`
https://ci.ros2.org/job/ci_osx/3762

Maybe a recent update reenabled SIP ?

@clalancette as build cop

**Comment by clalancette** [comment]
SIP is still nominally disabled:

```
$ csrutil status
System Integrity Protection status: disabled.
```

After the current CI job on it finishes, I'm going to take it offline and poke at it a bit.

**Comment by mikaelarguedas** [comment]
That seems like the issue then. SIP should be enabled for us not taking the performance hit, isn't it ?

Is SIP enabled on the other MacOS nodes?

**Comment by clalancette** [comment]
> Is SIP enabled on the other MacOS nodes?

SIP is currently disabled on all 3 of our MacOS nodes.  Our tutorials also suggest to disable it, here: https://github.com/ros2/ros2/wiki/OSX-Development-Setup#disable-system-integrity-protection-sip .

I'm honestly not sure where we ended up the last time we debugged this; I'll have to go looking through the issues/logs for that.

**Comment by nuclearsandwich** [comment]
> That seems like the issue then. SIP should be enabled for us not taking the performance hit, isn't it ?

My memory is that the performance impact from disabling SIP was only present (or extreme) on MacOS High Sierra and that Sierra and El Capitan were still able to run without SIP.

We explored several options on High Sierra when working with Dosa including trying to only disable certain sub-components of SIP and trying to identify the source of the performance issues. Eventually we retired Dosa, replaced it with new hardware (as @wjwwoods' macbook never seemed to exhibit the performance issues) and were disappointed to see the performance issues return https://github.com/ros2/build_cop/issues/102 The eventual solution was to run Mac OS Sierra on all nodes and put off dealing with High Sierra.

To my knowledge the last MacOS updates brought us to 10.12.6 on 16 May. The most recent packaging job from mini2 which had expected runtime looks to be https://ci.ros2.org/job/packaging_osx/1050/ the last ci_osx job before the runtime spike looks to be https://ci.ros2.org/job/ci_osx/3756/ I haven't examined parameters for any of the linked jobs so they may not be comparable.

**Comment by clalancette** [comment]
Actually, looking at the node closer, it looks like it is probably slow because there are 11 processes called `initial_params_rclcpp` taking up basically all of the CPU time.  I'm going to cancel the current job on it (since it is never going to succeed), take the node offline, and do some repairs.

**Comment by clalancette** [comment]
I've now killed off the processes that were taking all of the CPU time, rebooted the node for good measure, logged it in the build farmer sheet, and brought it back online.  This should be fixed now, so I'm going to close this out; feel free to reopen if we see this start happening again.
