### ISSUE TITLE
Launch tests on Linux fail on repeated

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#126]
When running repeated jobs under Linux, there are some test failures with `launch_testing.test.test_env_passing.test_env`, like in this job: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/454 .  @wjwwood Probably worth looking into.

**Comment by dhood** [comment]
I think I saw you already had a conversation about this in slack right? Can you summarise that here? It sounded more like a pytest issue than any of the launch changes (which came after this appeared)

**Comment by clalancette** [comment]
Not much of a conversation; I just poked @wjwwood about it.  He might have a better idea, but I haven't looked into it any further.

**Comment by clalancette** [comment]
This continues to fail: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/470

**Comment by clalancette** [comment]
This is still a problem (both amd64 and arm64): https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/624

**Comment by sloretz** [comment]
Still a problem on all platforms

https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/707/#showFailuresLink
https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1457/#showFailuresLink
https://ci.ros2.org/view/nightly/job/nightly_win_rep/1384/#showFailuresLink
https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1308/#showFailuresLink

**Comment by dirk-thomas** [comment]
See ros2/launch#200 for a fix.

**Comment by dirk-thomas** [comment]
Addressed during #168.
