### ISSUE TITLE
Linux Opensplice jobs are flaky for test_publisher_subscriber_{Builtins,Primitives,Empty}

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#127]
Linux Opensplice jobs sometimes fail the `test_publisher_subscriber_{Builtins,Primitives,Empty}` tests, like in https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_ospl_release/15/ .  I think this is an ongoing flakiness, but we should probably look into it eventually.

**Comment by clalancette** [comment]
Last night they also failed for all OpenSplice jobs on `test_requester_replier_{Empty,Primitives}`: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_ospl_release/21.  It may or may not be related.

**Comment by clalancette** [comment]
Another example: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_ospl_release/22/testReport/junit/test_communication.build.test_communication/test_requester_replier__Empty__rclpy__rmw_opensplice_cpp_Release/test_requester_replier/

**Comment by mikaelarguedas** [comment]
The original issue happens only with opensplice talking to fastrtps and was originally described at https://github.com/ros2/ros2/issues/476#issuecomment-393016134

As the service tests are consistently failing (on amd64 as well) and it started 2 days ago, I think this is a separate issue that should be tracked in another ticket with the list of potential culprit PRs for the day before the failure appeared

**Comment by dhood** [comment]
the failing empty requester-replier opensplice tests were resolved by https://github.com/ros2/rclpy/pull/194 e.g. https://ci.ros2.org/view/nightly/job/nightly_linux_ospl_release/25/

**Comment by clalancette** [comment]
I haven't seen this in over 2 weeks, so closing.
