### ISSUE TITLE
Linux aarch64 repeated tests failed image_tools testing

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#129]
In the latest Linux aarch64 repeated test, the image_tools tests failed: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/454 .  I remember something like this happening in the past, but I couldn't find another open ticket tracking it, so opening this one.  @dhood , I know you have looked at this in the past, so if you have time to look at it, it might be good.  Otherwise, @ros2/team to triage it and maybe fix it later.

**Comment by dhood** [comment]
I'd suspect it's another instance of nodes not shutting down properly as in https://github.com/ros2/build_cop/issues/118 that leads to timeouts. Will run a build that doesn't capture console output to check

**Comment by clalancette** [comment]
I haven't seen this one in over 2 weeks.  If @dhood is correct, then we'll see it again, but closing for now.
