### ISSUE TITLE
Flaky fastrtps security test

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#130]
Last night the aarch64 repeated test failed running the `secure_not_connecting_1` test: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/454 .  We should probably look into it to see what happened.  @mikaelarguedas I know you are busy, so this is just an FYI.  @ros2/team otherwise to look into it.

**Comment by dhood** [comment]
These have been flaky for a long time FWIR eg referenced in https://github.com/ros2/build_cop/issues/41

**Comment by clalancette** [comment]
Cool, good to know.  I'll leave this open for tracking the flakiness then.

**Comment by mikaelarguedas** [comment]
@clalancette this looks to be an issue of nodes not shutting down properly. I don't think this should be tracked as an individual flaky test as this happens on other packages and tests. It would be better tracked as a generic issue with reference to multiple tests faiiling this way that need investigation

**Comment by clalancette** [comment]
OK, done in #132.  Closing this one out.
