### ISSUE TITLE
OSX multi-threaded executor test failed

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#131]
Last night the multi-threaded executor test failed on macOS: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/897/ .  This may be related to the ongoing timer problems we've had, but I'm not sure.

**Comment by mjcarroll** [comment]
This is related to the PR that I landed last night. ros2/rclcpp#383

The last thing I did on the PR was expand the tolerance, so I wouldn't expect it to fail, but I will look into it.

**Comment by dhood** [comment]
In case you didn't notice already @mjcarroll this was on a debug build

**Comment by mjcarroll** [comment]
It also seems to manifest in nightly_osx_repeated.  I _think_ that it's poor test conditions.

**Comment by mjcarroll** [comment]
https://github.com/ros2/rclcpp/pull/501

**Comment by mjcarroll** [comment]
ros2/rclcpp#501 is merged, this should be resolved.
