### ISSUE TITLE
Flaky test shutdown

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#132]
We've seen several instances over time of tests that seem to succeed, but throw some kind of error when they are sent the signal to quit.  Some instances of this problem are:

* https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/454/testReport/junit/(root)/projectroot/test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_not_connecting_1/ (subscriber crashed with '1' after successfully doing callback)
* https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/456/testReport/junit/(root)/projectroot/test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_not_connecting_1/ (publisher crashed with '-11')

**Comment by mikaelarguedas** [comment]
These seem to be 2 pretty different failures:
the first one the test genuinely failed (because it received message it shouldnt have likelly from zombie node)
The second on the test passed and the publisher crashed with a segfault when shutting down

**Comment by clalancette** [comment]
I'm going to close this out and open different issues to track these.
