### ISSUE TITLE
Build Farmer Handoff 2018-07-11

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#140]
Outgoing: @clalancette from #122 
Incoming: @wjwwood 

#### Build Cop tasks
* composition test flakiness increase (to be investigated) #118
* pendulum tests fail on aarch64 opensplice #133 
* launch testing failures on linux repeated #126 
* Windows repeated test_timer_callbacks is flaky #139 
* Windows Opensplice test_graph test is flaky #138 
* Services/parameter tests with Fast-RTPS are flaky on aarch64 #136 
* Fast-RTPS get_node_names flaky on aarch64 #135 

#### Build farmer tasks
* Update Java to 1.8u162 on all hosts (including master): @nuclearsandwich
* Periodic upgrades on Mac and Windows: Build farmer (last done near beginning of June)
* Profile memory usage of bridge compilation job #106 (failures currently resolved by increasing instance size)
* I saw an uptick in occurrences of #45, almost all of them on OSX.  Should be investigated.
* Update macOS to Python 3.7, deal with the fallout

**Comment by mikaelarguedas** [comment]
We need to deal with Python 3.7 on Windows as well, see if we can build the debug version etc

**Comment by wjwwood** [comment]
Thanks for the hand-off issue @clalancette. I'm going to close this and track them individually. The Python3.7 is done now I think as well.
