### ISSUE TITLE
Bouncy Patch 1 Upgrades

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#141]
On macOS I updated things with `brew update; brew upgrade; brew cleanup`:

- mini1 (after updating: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=85)](https://ci.ros2.org/job/test_ci_osx/85/)):
```
mini1:~ osrf$ brew upgrade
==> Upgrading 15 outdated packages, with result:
cmake 3.11.3 -> 3.11.4, cppcheck 1.83 -> 1.84, ffmpeg 4.0 -> 4.0.1, gdbm 1.14.1_1 -> 1.16, libtiff 4.0.9_3 -> 4.0.9_4, llvm 6.0.0 -> 6.0.1, mercurial 4.6.1 -> 4.6.2, numpy 1.14.4 -> 1.14.5_1, opencv 3.4.1_5 -> 3.4.2, openssl 1.0.2o_1 -> 1.0.2o_2, python 3.6.5 -> 3.7.0, python@2 2.7.15 -> 2.7.15_1, qt 5.11.0 -> 5.11.1, readline 7.0.3_1 -> 7.0.5, tbb 2018_U4 -> 2018_U5
```
- mini2 (after updating: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=82)](https://ci.ros2.org/job/test_ci_osx/82/)):
```
mini2:~ osrf$ brew upgrade
==> Upgrading 14 outdated packages, with result:
cmake 3.11.3 -> 3.11.4, cppcheck 1.83 -> 1.84, ffmpeg 4.0 -> 4.0.1, gdbm 1.14.1_1 -> 1.16, libtiff 4.0.9_3 -> 4.0.9_4, mercurial 4.6.1 -> 4.6.2, numpy 1.14.4 -> 1.14.5_1, opencv 3.4.1_5 -> 3.4.2, openssl 1.0.2o_1 -> 1.0.2o_2, python 3.6.5 -> 3.7.0, python@2 2.7.15 -> 2.7.15_1, qt 5.11.0 -> 5.11.1, readline 7.0.3_1 -> 7.0.5, tbb 2018_U4 -> 2018_U5
```
- mini3 (after updating: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=83)](https://ci.ros2.org/job/test_ci_osx/83/)):
```
mini3:~ osrf$ brew upgrade
==> Upgrading 14 outdated packages, with result:
cmake 3.11.3 -> 3.11.4, cppcheck 1.83 -> 1.84, ffmpeg 4.0 -> 4.0.1, gdbm 1.14.1_1 -> 1.16, libtiff 4.0.9_3 -> 4.0.9_4, mercurial 4.6.1 -> 4.6.2, numpy 1.14.4 -> 1.14.5_1, opencv 3.4.1_5 -> 3.4.2, openssl 1.0.2o_1 -> 1.0.2o_2, python 3.6.5 -> 3.7.0, python@2 2.7.15 -> 2.7.15_1, qt 5.11.0 -> 5.11.1, readline 7.0.3_1 -> 7.0.5, tbb 2018_U4 -> 2018_U5
```

I also did system updates on `mini1` and `mini3`.

**Comment by mikaelarguedas** [comment]
Piggy backing on this post with Windows upgrades:

Upgrades performed on icecube, portable and windshield:
cmake 3.11.3 -> 3.11.4
cmake.install 3.11.3 -> 3.11.4
cppcheck 1.82.0 -> 1.84.0.2
curl 7.60.0 -> 7.61.0
git 2.17.1.2 -> 2.18.0
git.install 2.17.1.2 -> 2.18.0
 
Also performed system updates (detailed in logbook)

CI jobs:
icecube: [![Build Status](https://ci.ros2.org/job/test_ci_windows/14//badge/icon)](https://ci.ros2.org/job/test_ci_windows/14/)
portable: [![Build Status](https://ci.ros2.org/job/test_ci_windows/12//badge/icon)](https://ci.ros2.org/job/test_ci_windows/12/)
windshield: [![Build Status](https://ci.ros2.org/job/test_ci_windows/13//badge/icon)](https://ci.ros2.org/job/test_ci_windows/13/)

**Comment by wjwwood** [comment]
Upgrades are complete and look to have caused no regressions.
