### ISSUE TITLE
macOS packaging job failure

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#142]
See: https://ci.ros2.org/view/packaging/job/packaging_osx/1094/console

It looks like a bug in the CI scripts. Investigating now.

**Comment by mikaelarguedas** [comment]
Maybe related, we upgraded to python3.7 yesterday.
That would explain why we didnt see it on windows (upgraded last week) because this code path is used only for linux/macos

**Comment by dirk-thomas** [comment]
> Maybe related, we upgraded to python3.7 yesterday.

Certainly, the argument was deprecated for a while and got removed in 3.7: https://docs.python.org/3.6/library/tarfile.html#tarfile.TarFile.add

**Comment by wjwwood** [comment]
I have a patch, just testing it now.

**Comment by wjwwood** [comment]
https://github.com/ros2/ci/pull/210
