### ISSUE TITLE
Missing cv_bridge MacOS dependency boost_python3

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#146]
When trying to build cv_bridge in CI i have a missing `boost_python3` dependency.

https://ci.ros2.org/job/ci_osx/4209/console#console-section-6

Looking for permission/authority to get this dependency satisfied on MacOS.

**Comment by nuclearsandwich** [comment]
Is https://formulae.brew.sh/formula/boost-python3 the correct package to satisfy that dependency?

**Comment by dirk-thomas** [comment]
Since `cv_bridge` is not part of the `ros2.repos` file atm I will go ahead and close this ticket. If it is proposed to be added it needs to pass across all platforms.
