### ISSUE TITLE
Build Farmer handoff 2018-10-11

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#148]
Outgoing: @nuclearsandwich from #145 
Incoming: @mjcarroll   

#### Known flaky tests and recurring failures
* rviz tests are failing on aarch64 linux repeated (original contributors aware) #144
* composition test flakiness increase (to be investigated) #118
* pendulum tests fail on aarch64 opensplice #133 
* launch testing failures on linux repeated #126
* Windows repeated test_timer_callbacks is flaky #139 
* Windows Opensplice test_graph test is flaky #138 
* Services/parameter tests with Fast-RTPS are flaky on aarch64 #136 

#### Outstanding buildfarmer tasks

* Periodic upgrades on Mac and Windows: Build farmer (last done early October, aim for week 2 or 3 of your shift)
* Profile memory usage of bridge compilation job #106 (failures currently resolved by increasing instance size)
* Working theory for #45. No new incidents.

**Comment by dirk-thomas** [comment]
@mjcarroll The packaging seems to have new failing tests since 6 days, also several of the nightly jobs are yellow since a couple of days.

**Comment by mjcarroll** [comment]
I think that the warnings were introduced by @wjwwood's work on `rcutils`, I have opened an issue here: https://github.com/ros2/rcutils/issues/123

**Comment by dirk-thomas** [comment]
There seem to be several other jobs with warning and/or failing tests which are not related to that specific case.

**Comment by mjcarroll** [comment]
It additionally looks like all arm builds are failing, looking into that as well.

**Comment by mjcarroll** [comment]
The `nightly_*_extra_` failures are being worked here: #150

**Comment by dirk-thomas** [comment]
[OpenSplice 6.9 2018-11-27](https://github.com/ADLINK-IST/opensplice/releases/tag/OSPL_V6_9_181127OSS_RELEASE) has been installed on the macOS and Windows nodes.
