### ISSUE TITLE
Python message generation flake8 warnings for all platforms

### ISSUE THREAD

**Issue by jacobperron** [ros2/build_farmer#149]
Example build (packages up to `test_msgs`) with master branches:

https://ci.ros2.org/job/ci_linux/5337/

Error messages of the form:

```
line break after binary operator:
                 not isinstance(value, FooType) and
```

**Comment by sloretz** [comment]
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

Looks like the linter wants the `and` to begin the next line

**Comment by jacobperron** [comment]
I updated what I suspected to be the culprit lines, but on my machine it wants the opposite :laughing: 

```
    line break before binary operator:
                      or isinstance(value, UserList))
```

...maybe there was a recent change that I am missing?

**Comment by dirk-thomas** [comment]
The new release of `flake8` [3.6.0](http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html) is fairly new: 2018-10-23 aka yesterday. It bumps the version of `pycodestyle` to 2.4.x which includes this change: https://github.com/PyCQA/pycodestyle/blob/c3d2cbd744236c3a41d1013c9dce2712dcc4eee0/CHANGES.txt#L16-L17 From the docs it reads like this should be disabled by default which doesn't seem to match what we see...

**Comment by jacobperron** [comment]
Yep, after upgrading flake8 locally I see the same errors as the CI.

**Comment by jacobperron** [comment]
Can we add an ignore line to [ament_flake8](https://github.com/ament/ament_lint/blob/master/ament_flake8/ament_flake8/configuration/ament_flake8.ini)?

**Comment by dirk-thomas** [comment]
First we should figure out why the behavior we see doesn't match the documented one:

> Add W504 warning for checking that a break doesn't happen after a binary operator. This check is ignored by default. PR #502.

**Comment by jacobperron** [comment]
It looks like if we provide our own ignore options (as ament_flake8 does), then the default ignore values are ... ignored:

https://github.com/PyCQA/pycodestyle/blob/c3d2cbd744236c3a41d1013c9dce2712dcc4eee0/pycodestyle.py#L2271-L2277

**Comment by jacobperron** [comment]
If someone grants me permission for the ament repos I can push a fix :smile:

**Comment by dirk-thomas** [comment]
> If someone grants me permission for the ament repos ...

Done.
