### ISSUE TITLE
OSX nightly release build failed a tf2 test

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#15]
This job: http://ci.ros2.org/view/nightly/job/nightly_osx_release/433/

@dhood and @clalancette both pushed some changes to tf2 yesterday, so either one of those could be at fault.  However, in both cases the CI was green before the push, so it is odd that this failed.  Also, this particular test did not fail on the other OSs.  We need to look into this and figure out what is going on.

**Comment by clalancette** [comment]
FYI, I started looking into this a bit.  I'll report back progress.

**Comment by clalancette** [comment]
I just opened a PR: ros2/geometry2#18 .  That PR definitely fixes a bug, but whether it is this bug is not clear to me yet.

**Comment by dhood** [comment]
I'm going to close this under the supposition that https://github.com/ros2/geometry2/pull/18 has corrected this.
