### ISSUE TITLE
test_params_yaml flaky

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#155]
Last night it looks like the test_params_yaml test failed on nightly_win_rep: https://ci.ros2.org/view/nightly/job/nightly_win_rep/1299

**Comment by dirk-thomas** [comment]
The test is flaky across all platforms.

**Comment by jacobperron** [comment]
I tried running the test repeatedly while stressing my cpu. The test passes every time, but takes about 70-100 seconds to complete. Maybe we should limit the number of packages looped over in the test and/or increase the test timeout.

**Comment by dirk-thomas** [comment]
During my testing when the test failed it was hanging at one of the tests forever. So I don't think increasing the timeout will solve this problem but please feel free to try it.

**Comment by jacobperron** [comment]
Ignore my previous comment. I was running the wrong test...

**Comment by dirk-thomas** [comment]
Closing as duplicate of #166 which contains more information.
