### ISSUE TITLE
Uncrustify unit test failed on windows when repeated

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#16]
An uncrustify unit test failed on the 13th retry on the windows repeated job last night:
http://ci.ros2.org/job/nightly_win_rep/629/testReport/junit/projectroot/tests/test_uncrustify/

```
Stacktrace

Tests: ['c-sharp', 'c', 'cpp', 'd', 'java', 'pawn', 'objective-c', 'vala', 'ecma']
Processing c-sharp.test
Processing c.test
FAILED2: 01021
UNSTABLE: 02100
UNSTABLE: 02102
Processing cpp.test
UNSTABLE: 30265
UNSTABLE: 30815
Processing d.test
Processing java.test
Processing pawn.test
Processing objective-c.test
UNSTABLE: 50007
Processing vala.test
Processing ecma.test
Passed 615 / 616 tests
Failed 1 test(s)
```

I opened https://github.com/ament/uncrustify/issues/16 but won't spend more time fixing this.

**Comment by dirk-thomas** [comment]
I don't think this is a problem with the linter. I would suggest to check the Windows node that services like Windows Defender are not interfering. The Jenkins folder should simply be excluded in order to not be scanned and locking files temporarily.

**Comment by dhood** [comment]
thanks for the pointer @dirk-thomas. Indeed Portable (the machine that the two failures happened on) and Icecube hadn't been configured to exclude that folder for Windows Defender, unlike Windshield and Eatable. I added the exclusion and hopefully we won't see this again.

This job (windshield) [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2650)](http://ci.ros2.org/job/ci_windows/2650/) and this job (portable) [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2651)](http://ci.ros2.org/job/ci_windows/2651/) ran that test 100 times without failures so I'll close this for now.

**Comment by mikaelarguedas** [comment]
@dhood can you add this to the windows node installation instructions so that we don't forget when setting up new machines?

**Comment by dhood** [comment]
yes, I have
