### ISSUE TITLE
Build farmer handoff 2019-01-16

### ISSUE THREAD

**Issue by jacobperron** [ros2/build_farmer#160]
Outgoing @jacobperron from #151 
Incoming @sloretz 

#### Known flaky tests and recurring failures

* linux_nightly_coverage qt_gui_cpp test fails #158
* rviz tests are failing on aarch64 linux repeated (original contributors aware) #144
* composition test flakiness increase (to be investigated) #118
* pendulum tests fail on aarch64 opensplice #133 
* launch testing failures on linux repeated #126
* Windows Opensplice test_graph test is flaky #138 
  * (Possibly related) Missing test results #159 
* Services/parameter tests with Fast-RTPS are flaky on aarch64 #136 

#### Outstanding buildfarmer tasks

* Periodic upgrades on Mac and Windows
* Profile memory usage of bridge compilation job #106 (failures currently resolved by increasing instance size)

**Comment by clalancette** [comment]
I'll also point out that mini2 is still "offline", which causes a bit of a backup in the macOS jobs.

**Comment by jacobperron** [comment]
> I'll also point out that mini2 is still "offline", which causes a bit of a backup in the macOS jobs.

That's my bad. I'll put it back online.

**Comment by sloretz** [comment]
Replaced by #168
