### ISSUE TITLE
Try out Visual Studio 2019

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#162]
Visual Studio 2019 is supposed to be released [in the first half of 2019](https://blogs.msdn.microsoft.com/visualstudio/2018/10/17/visual-studio-roadmap-updates-and-visual-studio-2019-information/). This is a task to try it on a windows node and see if we should upgrade to it before the next release.

**Comment by dirk-thomas** [comment]
ros2/ci#276

**Comment by dirk-thomas** [comment]
Deployed.
