### ISSUE TITLE
nightly Windows job failing due to lxml

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#169]
Since the merge of ros2/sros2#72 the nightly Windows job is failing. It seems to be due to the new dependency on `lxml`.

@mjcarroll Since you merged the change please address the problem asap.

---

Just for the record: #168.

**Comment by mjcarroll** [comment]
On it.

**Comment by dirk-thomas** [comment]
The same still happens on non-nightly jobs: e.g. https://ci.ros2.org/job/ci_windows/6214/

**Comment by dirk-thomas** [comment]
Fixed by ros2/ci#261.

The latest nightly passed again: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1126/
