### ISSUE TITLE
cppcheck warning nullPointer in rclcpp clock.cpp

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#172]
After updating the `cppcheck` version this new warning appeared (https://ci.ros2.org/view/nightly/job/nightly_win_extra_rmw_rel/278/testReport/rclcpp/cppcheck/warning__nullPointer__src_rclcpp_clock_cpp_139_/):

```
rclcpp.cppcheck.warning: nullPointer (src\rclcpp\clock.cpp:139)
Possible null pointer dereference: handler
```

Same on macOS: https://ci.ros2.org/view/nightly/job/nightly_osx_extra_rmw_release/313/testReport/rclcpp/cppcheck/warning__nullPointer__src_rclcpp_clock_cpp_139_/
---

Just for the record: #168.

**Comment by sloretz** [comment]
fixed by #646
