### ISSUE TITLE
Build farmer handoff 2019-04-15

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#178]
Outgoing @dirk-thomas from #168 
Incoming @clalancette  

#### Known flaky tests and recurring failures

* Some builds fail to wipe the workspace due to processes from previous builds still running #161 
* `run_ros2_batch.py` sometimes not found on aarch64 #177
* `test_params_yaml` is flaky across all platforms #166
* Services/parameter tests with Fast-RTPS are flaky on aarch64 #136 
* Pendulum tests fail on aarch64 with OpenSplice #133 

#### Outstanding buildfarmer tasks

* Periodic upgrades on Mac and Windows
   * mini1/mini2/mini3/icecube/portable upgraded Feb 28, 2019
   * windshield upgraded Mar 01, 2019

**Comment by dirk-thomas** [comment]
I installed `xmllint` on all Windows nodes following these instructions: ros2/ros2_documentation#184.

*Update:* use 64 bit version to not conflict with `curl`.

**Comment by clalancette** [comment]
Closing for handoff to @wjwwood via #216
