### ISSUE TITLE
Flake8 errors on nightly jobs

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#179]
There are new flake8 errors on the nightly jobs; here's one example: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/788/testReport/junit/rosidl_generator_py/flake8_rosidl_generated_py/Q003___home_jenkins_workspace_nightly_linux_aarch64_debug_ws_build_rosidl_generator_py_rosidl_generator_py_rosidl_generator_py_msg__strings_py_45_37_/

It's not entirely clear to me where that change is coming from; there were two patches merged into rosidl stuff on April 16 ([here](https://github.com/ros2/rosidl_python/commit/e905f75914a9b2c6f2272766eb18618a17355882) and [here](https://github.com/ros2/rosidl/commit/d7fe618333bcb56777faedca5846721e640f75af)), but both seem to be benign.  Needs to be looked into.

**Comment by dirk-thomas** [comment]
> There are new flake8 errors on the nightly jobs; here's one example: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/788/testReport/junit/(root)/projectroot/flake8_rosidl_generated_py/ .

The page you referenced shows "Passed" for me?

**Comment by clalancette** [comment]
Hm, weird, I must have pasted the wrong URL.  I'll update the description.

**Comment by dirk-thomas** [comment]
> It's not entirely clear to me where that change is coming from

The new `Q003` `flake8` warnings seem to be related to the new release of `flake8-quotes` version 2.0.0: https://pypi.org/project/flake8-quotes/

> Needs to be looked into.

It should be straight forward to address the reported cases.

**Comment by dirk-thomas** [comment]
> I'll update the description.

The updated description still points to a page showing "Passed" for me?

**Comment by clalancette** [comment]
> The updated description still points to a page showing "Passed" for me?

I have no idea; when I test the link locally the first time, it points the right place, and then after I post it, it points to a passed test.  I'll try one more time, otherwise I'll just post a link to one of the build numbers.

**Comment by clalancette** [comment]
CI run here, as it requires all linked PRs to be successful:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6730)](http://ci.ros2.org/job/ci_linux/6730/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3043)](http://ci.ros2.org/job/ci_linux-aarch64/3043/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5532)](http://ci.ros2.org/job/ci_osx/5532/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6559)](http://ci.ros2.org/job/ci_windows/6559/)

**Comment by dirk-thomas** [comment]
@clalancette Can this ticket be closed?

**Comment by clalancette** [comment]
Yes, good point, closing now.
