### ISSUE TITLE
document how to set up and access aarch64 machine

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#18]
The packet.net machine is down and I can't fine documentation on how to access it to revive it

**Comment by gerkey** [comment]
Is there equivalent documentation somewhere for how to access the AWS-hosted machines and/or the physical machines that are in the farm?

**Comment by mikaelarguedas** [comment]
Right now everything is on the build farmer bible / guide. It should land on the wiki in the near future

**Comment by gerkey** [comment]
I added info on managing and accessing those servers to the bible doc. The SSH key info is incomplete, but will improve over time.

**Comment by mikaelarguedas** [comment]
Thanks!
