### ISSUE TITLE
test_component_manager_api failed on Linux repeated

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#184]
It looks like test_component_manager_api failed on Linux repeated: https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1360/testReport/junit/(root)/projectroot/test_component_manager_api/ ; the error is:

```
[ RUN      ] TestComponentManager.list_components
[INFO] [ComponentManager]: Load Library: /home/jenkins-agent/workspace/nightly_linux_repeated/ws/build/rclcpp_components/libtest_component.so
[INFO] [ComponentManager]: Found class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentBar>
[INFO] [ComponentManager]: Found class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentFoo>
[INFO] [ComponentManager]: Instantiate class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentFoo>
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rclcpp/rclcpp_components/test/test_component_manager_api.cpp:198: Failure
Expected equality of these values:
  ret
    Which is: TIMEOUT (2)
  rclcpp::executor::FutureReturnCode::SUCCESS
    Which is: SUCCESS (0)
```

@mjcarroll FYI

**Comment by clalancette** [comment]
There was also a failure on macOS repeated, though it is unclear whether this is related: https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1509/testReport/junit/(root)/projectroot/test_component_manager_api/

```
[ RUN      ] TestComponentManager.unload_component
[INFO] [ComponentManager]: Load Library: /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/build/rclcpp_components/libtest_component.dylib
[INFO] [ComponentManager]: Found class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentBar>
[INFO] [ComponentManager]: Found class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentFoo>
[INFO] [ComponentManager]: Instantiate class: rclcpp_components::NodeFactoryTemplate<test_rclcpp_components::TestComponentFoo>
/Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rclcpp/rclcpp_components/test/test_component_manager_api.cpp:254: Failure
Expected equality of these values:
  ret
    Which is: TIMEOUT (2)
  rclcpp::executor::FutureReturnCode::SUCCESS
    Which is: SUCCESS (0)
```

**Comment by mjcarroll** [comment]
This is possibly related to: https://github.com/ros2/ros2cli/issues/221

**Comment by clalancette** [comment]
This one was still a problem over the weekend: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/786/testReport/junit/(root)/projectroot/test_component_manager_api/

**Comment by hidmic** [comment]
Popped up again in a dashing backport PR job: http://build.ros2.org/view/Ddev/job/Ddev__rclcpp__ubuntu_bionic_amd64/45/testReport/ but this time it didn't even generate a test result file hmm...

**Comment by tfoote** [comment]
We're seeing repeatedly in the pull request jobs here: https://github.com/ros2/rclcpp/pull/857

and in https://github.com/ros2/rclcpp/pull/862 the timeout has been removed and it still doesn't complete which make it look more like a real underlying problem that we should debug. However previous PR jobs also had the same issue. Something in how they're run is triggering it more often.

**Comment by mjcarroll** [comment]
Sorry this fell off my radar, I'm promoting it to a bug report over here: https://github.com/ros2/rclcpp/issues/863 since it has recently impacted us.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
