### ISSUE TITLE
rmw_fastrtps_dynamic_cpp communication tests are failing

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#190]
One example is: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_extra_rmw_release/341/testReport/junit/(root)/projectroot/test_publisher_subscriber__rclpy__rmw_fastrtps_cpp__rmw_fastrtps_dynamic_cpp/

When it fails, there is a message that says:

```
[test_subscriber-24] terminate called after throwing an instance of 'std::runtime_error'
INFO:test_subscriber-24-stderr:[test_subscriber-24] terminate called after throwing an instance of 'std::runtime_error'
[test_subscriber-24]   what():  unknown type
```

And then the whole process goes down.

**Comment by dirk-thomas** [comment]
The error happens on `WStrings`. This looks like something is missing for wstring in RMW FastRTPS dynamic...
