### ISSUE TITLE
Windows release stack corruption

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#191]
In release mode, the Windows nightly builds are sometimes failing: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1181/testReport/junit/(root)/projectroot/test_publisher_subscriber__rclpy__rclcpp__rmw_connext_cpp/ .  From what @hidmic has said, it looks like only an issue when communicating between rclcpp <-> rclpy, and only on Windows in release mode.  I believe @hidmic is looking into it, so I'm going to assign him for now.

**Comment by dirk-thomas** [comment]
The error happens on `WStrings`.

**Comment by clalancette** [comment]
This one seems to be fixed on the nightlies: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1183/#showFailuresLink .  Closing.

**Comment by dirk-thomas** [comment]
> Closing.

Please include links to PRs which addressed the problem.

In this case this ticket seems to be a duplicate of ros2/system_tests#359 which already contains references to the involved PRs.
