### ISSUE TITLE
Nightly linux debug remapping tests failed

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#194]
Several of the remapping tests failed on nightly_linux_debug: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1192.  One of them also failed on aarch64, though only on the repeated job.

Here's a direct link to one of the failures: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1192/testReport/junit/test_cli_remapping/TestCLIRemapping/test_service_replacement__home_jenkins_agent_workspace_nightly_linux_debug_ws_build_test_cli_remapping_name_maker_rclcpp_/

**Comment by clalancette** [comment]
This one also failed last night on aarch64-debug: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/818/#showFailuresLink

This one is probably important to look at and fix; @ros2/team are there any volunteers to look at this one?

**Comment by nuclearsandwich** [comment]
I have reproduced this locally and on CI. It's flakey, I can see it pass with --retest-until-pass 10, and see it fail with --retest-until-fail 10. I've been running just the `topic_and_service_replacement` test locally in Linux-debug and see similar flakiness.

I paused the test with pdb during a failed run. From the debugger, `node.get_topic_names_and_types()` is missing topics that do appear when running `ros2 topic list` in another terminal window. Creating a new node from within the debugger and calling `newnode.get_topic_names_and_types()` also shows the topics missing from the test node.

**Comment by nuclearsandwich** [comment]
Well as I tried to dig into this more through the afternoon I saw more instances of the remapped topic not being present in `ros2 topic list` than I did of `ros2 topic list` showing the remapped topic while the test node did not.

**Comment by clalancette** [comment]
The last time I saw this on any platform was May 20th.  Nevertheless, since it is flakey, I'm going to leave this open for another few days to see if it comes back.

**Comment by clalancette** [comment]
This came back on aarch64 last night, so it is still a problem: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/825/

**Comment by clalancette** [comment]
This hasn't happened since August 26 (the furthest back I was willing to go looking for it).  I'm going to close it out; we can reopen if it becomes a problem again.
