### ISSUE TITLE
talker_listener.test.py from Linux aarch64 debug failed nightly

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#197]
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/816/testReport/junit/launch_testing_ros.test/test_examples/test_examples_talker_listener_test_py_/ failed the nightly test, where waiting for a response seemed to time out (search for "Waiting for output timed out" in the above).

**Comment by clalancette** [comment]
@hidmic I assigned this to you, but feel free to delegate.

**Comment by dirk-thomas** [comment]
ros2/rclpy#351 resolve the `TypeError` part of the traceback. The remaining problem is due to the fact that one of the test functions (https://github.com/ros2/launch_ros/blob/5c9262691cd9e1043baef8457cfbdb3f354c0cbe/launch_testing_ros/examples/talker_listener.test.py#L156) hangs on wait-for-output.
