### ISSUE TITLE
Nightly macOS test failure: test_parameter_server_cpp__rmw_fastrtps_cpp

### ISSUE THREAD

**Issue by jacobperron** [ros2/build_farmer#198]
The synchronous parameter service call test is timing out.
Occurs on both [nightly_osx_debug](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1251/testReport/(root)/projectroot/test_parameter_server_cpp__rmw_fastrtps_cpp/) and [nightly_osx_release](https://ci.ros2.org/view/nightly/job/nightly_osx_release/1259/testReport/junit/(root)/projectroot/test_parameter_server_cpp__rmw_fastrtps_cpp/).

This appears to be a recent failure (1 day old at the time of reporting).
This coincides with the release Fast-RTPS 1.8.

**Comment by jacobperron** [comment]
I've also seen this failure on [ci_windows](https://ci.ros2.org/job/ci_windows/6918/testReport/junit/(root)/projectroot/test_parameter_server_cpp__rmw_fastrtps_cpp/), though not in the recent nightly builds.

**Comment by dirk-thomas** [comment]
Could be related to #196?

**Comment by jacobperron** [comment]
> Could be related to #196?

Possibly :man_shrugging:

**Comment by dirk-thomas** [comment]
The new consistent failures in debug / release build are resolved by the reference fix. Closing this...
