### ISSUE TITLE
Add/change turtlebot demo to build on aarch64

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#20]
The current turtlebot_demo CI job runs on labels marked as "linux", which in our build farm is implicitly x86_64 machines.  However, the real turtlebot demo is almost certainly going to run on aarch64, so we should either change the label on the turtlebot-demo job to be "linux_aarch64", or we should add an additional job to build turtlebot-demo on both architectures.  @nuclearsandwich @gerkey does that make sense?

**Comment by dirk-thomas** [comment]
@clalancette I would suggest to fill this ticket in the ros2/ci repo instead. Can you please create a new ticket there and close this one.

**Comment by clalancette** [comment]
Oh right, I guess create_jenkins_job.py is responsible for this.  I'll open it up there, thanks.
