### ISSUE TITLE
Nightly Windows failed many tests using the launcher

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#200]
Many of the tests in the latest Windows nightly failed: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1253/#showFailuresLink

There are some failures there because it failed to resolve a symbol; those are fixed by https://github.com/ros2/rmw_connext/pull/355 and ignored here.  Of the remaining failures, most of them look like they failed to find rclpy._rclpy while launching:

```
 - C:/Python37/python.exe -m launch_testing.launch_test C:/J/workspace/nightly_win_deb/ws/build/image_tools/test_showimage_cam2image__rmw_connext_cpp_Debug.py --junit-xml=C:/J/workspace/nightly_win_deb/ws/build/image_tools/test_results/image_tools/test_showimage_cam2image__rmw_connext_cpp.xunit.xml --package-name=image_tools
usage: launch_test.py [-h] [--package-name PACKAGE_NAME] [-v] [-s] [-i]
                      [--junit-xml XMLPATH]
                      launch_test_file
                      [launch_arguments [launch_arguments ...]]
launch_test.py: error: No module named 'rclpy._rclpy'
-- run_test.py: return code 2
```

(the direct link to the failing test is https://ci.ros2.org/view/nightly/job/nightly_win_deb/1253/testReport/junit/(root)/projectroot/test_showimage_cam2image__rmw_connext_cpp/).  @hidmic I'm assigning to you, but feel free to delegate as needed.

**Comment by nuclearsandwich** [comment]
I can reproduce this on a Windows Server machine but I haven't figured out what's happening. My first reproduction of this issue was Tuesday 2019-05-07 but because no one else had seen it I assumed that it was a local configuration issue. I can build in Release configuration on the same host.

**Comment by jacobperron** [comment]
It would appear that the tests are not being invoked with the right Python executable.
For example, if I call a test with `python_d`, then the test runs without error:

```sh
python_d build\image_tools\test_showimage_cam2image__rmw_fastrtps_cpp_Debug.py
```

I'm not sure exactly where to fix this yet, any pointers are welcome.

**Comment by nuclearsandwich** [comment]
So my issue is different from the one in CI (and that @jacobperron has reproduced) since I can't run python_d and then `import rclpy._rclpy` as @jacobperron can. I also accessed last night's nightly_win_deb workspace on Windshield and verified that I can import it there using the python_d prompt.

**Comment by clalancette** [comment]
This still failed over the weekend: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1255/#showFailuresLink

**Comment by nuclearsandwich** [comment]
#239 was merged on Sunday which addresses this issue. That change resolves the big issue but introduced a new error (https://github.com/ros2/launch/pull/244#issuecomment-494035671)

**Comment by jacobperron** [comment]
https://github.com/ros2/launch/pull/239 resolves most of the failures (not the `rqt_py_common` test failures).

https://github.com/ros2/launch/pull/245 should resolve the new error.

And here is an attempt to resolve the `rqt_py_common` test failures: https://github.com/ros-visualization/rqt/pull/196

**Comment by clalancette** [comment]
The tests last night got rid of most of these errors, so thanks @jacobperron !  There are still some failures on Windows, but I'll ticket them separately, so I'll close this out.
