### ISSUE TITLE
Windows debug failed launch_testing_examples_args

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#202]
Last night there was a failure in Windows Debug with launch_testing_examples_args: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1257/testReport/junit/(root)/projectroot/C__J_workspace_nightly_win_deb_ws_install_share_launch_testing_examples_args_test_py/

This seems to be a new failure that I haven't seen before.  @hidmic @jacobperron any thoughts?

**Comment by jacobperron** [comment]
Yes, this was introduced by fixes for #200.

I had a proposed fix in https://github.com/ros2/launch/pull/245, but this caused a regression for Linux builds and was consequently reverted in https://github.com/ros2/launch/pull/247.

**Comment by jacobperron** [comment]
Fixed by ros2/launch#245 + ros2/launch#247.
