### ISSUE TITLE
Build farmer handoff 2019-06-11

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#216]
Outgoing @clalancette from #178 
Incoming @wjwwood 

#### Known flaky tests and recurring failures

* Pendulum tests fail on aarch64 with OpenSplice #133 
* Some builds fail to wipe the workspace due to processes from previous builds still running #161 
* gtest_multithreaded tests are flakey #180 
* tf2_ros_test_message_filter test is flakey #183 
* Linux test_component_manager fails on Linux repeated #184 
* Linux test_cli_remapping is flakey #194 
* Linux aarch64 test_parameter_server is flakey #201 
* Windows debug fails test_communications WString #203 
* Windows debug fails test_waitiable #204 
* Linux aarch64 test_lifecycle fails #205 
* rosbag2 test_play is flakey #210 
* Windows parameter tests are flakey #211 

#### Outstanding buildfarmer tasks

* Periodic upgrades on Mac and Windows
   * mini1/mini2/mini3/icecube/portable/windshield upgraded May 21, 2019

**Comment by wjwwood** [comment]
Closing with https://github.com/ros2/build_cop/issues/224.
