### ISSUE TITLE
ccache stats not incrementing after builds

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#219]
Each linux build agent has a local ccache that is mounted into the docker containers that run builds. To verify that ccache is being used we begin and end each build by printing out aggregated ccache stats (see the `ccache stats (before)` and `ccache stats (after)`) sections of the jenkins build logs.

Some recent jobs do not appear to show any ccache deltas (hit or miss)

* [ci_linux#7610](https://ci.ros2.org/job/ci_linux/7610/)
  * [before](https://ci.ros2.org/job/ci_linux/7610/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/job/ci_linux/7610/consoleFull#console-section-204)
* [ci_linux#7614](https://ci.ros2.org/job/ci_linux/7614/)
  * [before](https://ci.ros2.org/job/ci_linux/7614/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/job/ci_linux/7614/consoleFull#console-section-198)

Recent nightlies do show signs of ccache activity.

* [nightly_linux_debug](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1255/)
  * [before](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1255/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1255/consoleFull#console-section-794)

This could be related to the high churn of agent hosts lately due to AWS spot instance availability but that doesn't explain why ccache stats within a job are not increasing.

The current plan is to keep track of upcoming nightlies and CI runs to look for further occurrences.

**Comment by nuclearsandwich** [comment]
No ccache activity:

* ci_linux#7624
  * [before](https://ci.ros2.org/job/ci_linux/7624/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/job/ci_linux/7624/consoleFull#console-section-215)

16 ccache hits

* nightly_linux_release#1242
  * [before](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1242/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1242/consoleFull#console-section-790)
* nightly_linux_debug#1256
  * [before](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1256/consoleFull#console-section-7)
  * [after](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1256/consoleFull#console-section-790)

I feel like 16 ccache attempts for an entire nightly run is much too low. So although ccache is being used it seems far from ubiquitous which is worth investigating.

**Comment by dirk-thomas** [comment]
> I feel like 16 ccache attempts for an entire nightly run is much too low. So although ccache is being used it seems far from ubiquitous which is worth investigating.

The benefit of `ccache` is not during a single build. The majority of the advantage comes from the fact that a later build will have a high hit rate (assuming the same code is being built). So this is definitely worth investigating as soon as time allows since it is slowing down every (Linux) build.

See macOS builds for a comparison how much they safe: ros2/ci#320

**Comment by nuclearsandwich** [comment]
So at least part of the issue is that our linux hosts are not staying online and thus the ccache cannot populate. I don't think it's the whole issue but it's definitely part of the problem.

**Comment by nuclearsandwich** [comment]
https://github.com/ros2/ci/pull/326 addresses this issue. Once that has been merged and deployed and run for a few rounds of nightlies I'll update stats here and close this issue. For more info on why the fix is needed and where I'll eventually link the Debian bug I need to open watch that PR.

**Comment by nuclearsandwich** [comment]
A test job with ros2/ci#326 yielded the following stats:

```
# BEGIN SUBSECTION: ccache stats (before)
==> ccache -s
cache directory                     /home/rosbuild/.ccache
primary config                      /home/rosbuild/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats zero time                     Wed Aug 14 16:42:54 2019
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
preprocessor error                     1
cleanups performed                     0
files in cache                         0
cache size                           0.0 kB
max cache size                       5.0 GB
```

```
# BEGIN SUBSECTION: ccache stats (after)
cache directory                     /home/rosbuild/.ccache
primary config                      /home/rosbuild/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats zero time                     Wed Aug 14 16:42:54 2019
cache hit (direct)                   551
cache hit (preprocessed)             746
cache miss                          6496
cache hit rate                     16.64 %
called for link                     3390
called for preprocessing              93
compile failed                         2
preprocessor error                     3
cleanups performed                     0
files in cache                     12275
cache size                           1.7 GB
max cache size                       5.0 GB
```

Which is a much improved result.

**Comment by dirk-thomas** [comment]
A similar fix is needed for the CI jobs generated by `ros_buildfarm` (based on this comment: https://github.com/ros2/ci/pull/326#pullrequestreview-275136574).

**Comment by nuclearsandwich** [comment]
> A similar fix is needed for the CI jobs generated by `ros_buildfarm` (based on this comment: [ros2/ci#326 (review)](https://github.com/ros2/ci/pull/326#pullrequestreview-275136574)).

I put this on my queue along with getting a Debian bug open.

**Comment by nuclearsandwich** [comment]
> A similar fix is needed for the CI jobs generated by `ros_buildfarm` (based on this comment: [ros2/ci#326 (review)](https://github.com/ros2/ci/pull/326#pullrequestreview-275136574)).

So I went and checked the CI jobs and they appear to be picking up ccache symlinks fine. (Open http://build.ros2.org/view/Eci/job/Eci__nightly-release_ubuntu_bionic_amd64/57/consoleFull#console-section-1727 and search 'working C compiler')

I expect it's because ccache is installed in a separate later step of the devel task job from build-essential. However, general devel jobs don't appear to be making use of ccache so there's still work outstanding. I'm going to start by identifying an issue I can open upstream.

**Comment by dirk-thomas** [comment]
It doesn't seem to be the case for another CI job: http://build.ros.org/view/Nci/job/Nci__bionic-python2_ubuntu_bionic_amd64/9/

**Comment by nuclearsandwich** [comment]
PR to address the issue for Devel, PR, and CI jobs in ros_buildfarm https://github.com/ros-infrastructure/ros_buildfarm/pull/671

**Comment by nuclearsandwich** [comment]
The workaround is merged on both ros2/ci and ros_buildfarm. I need to learn more about the dpkg trigger system to figure out which package actually needs to change to fix what is essentially a race condition between the update-alternatives system and dpkg triggers. Hoping to ask my resident subject matter expert when they return from vacation.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
