### ISSUE TITLE
Java 8u131 on windows makes jenkins client crash

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#22]
I tried to update java on windshield. The jenkins client could not connect to the jenkins master after the update. I downgraded java to version 8u121 and it's back online. We need to investigate this before considering updating java on the ci machines

**Comment by wjwwood** [comment]
I upgraded java again when windshield went down a few days ago. It seems to be working, though. Maybe a reboot helped?

Either way it is updated and running now, so I'll close this.

<img width="330" alt="screen shot 2017-06-20 at 5 11 33 pm" src="https://user-images.githubusercontent.com/100427/27361343-9a556bf8-55db-11e7-9cd1-f7d09430395a.png">
