### ISSUE TITLE
test_find_container_node_names fails consistently on Windows

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#223]
See this consistent failure on Windows nightly:

https://ci.ros2.org/view/nightly/job/nightly_win_rel/1271/testReport/ros2component.test/test_api/test_find_container_node_names/

```
test\test_api.py:30: in test_find_container_node_names
    assert len(find_container_node_names(
ros2component\api\__init__.py:204: in find_container_node_names
    services = get_service_info(node=node, remote_node_name=n.full_name)
..\..\..\..\install\Lib\site-packages\ros2node\api\__init__.py:76: in get_service_info
    return get_topics(remote_node_name, node.get_service_names_and_types_by_node)
..\..\..\..\install\Lib\site-packages\ros2node\api\__init__.py:59: in get_topics
    names_and_types = func(node.name, node.namespace)
..\..\..\..\install\Lib\site-packages\rclpy\node.py:1500: in get_service_names_and_types_by_node
    capsule, node_name, node_namespace)
E   RuntimeError: Failed to get_service_names_and_types: Unable to find GUID for node , at C:\J\workspace\nightly_win_rel\ws\src\ros2\rmw_fastrtps\rmw_fastrtps_shared_cpp\src\rmw_node_info_and_types.cpp:87
```

I didn't find a root cause yet, nor an existing issue for this problem. I brought it up at the ROS 2 meeting and no one had investigated yet or had an idea.

**Comment by ivanpauno** [comment]
https://github.com/ros2/ros2cli/pull/322 together with related PRs should solve the problem.
I will check if it's solved after they are merged.

**Comment by ivanpauno** [comment]
https://github.com/ros2/ros2cli/pull/322 was merged, so this failure shouldn't happen again.
I will monitor a couple of days if the error doesn't appear again, and after that I will close

**Comment by ivanpauno** [comment]
@cottsay The failure didn't appear again in the last few days. Do you mind closing this? I don't have write access here.

**Comment by clalancette** [comment]
Closing...
