### ISSUE TITLE
Build farmer handoff 2019-08-07

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#224]
Outgoing @wjwwood, from #216
Incoming @cottsay 

#### Consistent failures (high priority)

* Failing test related to `emulate_tty` on Windows: https://github.com/ros2/launch/issues/298
* SROS2 test failure only on Windows: https://github.com/ros2/sros2/issues/143
* test_find_container_node_names fails consistently on Windows: https://github.com/ros2/build_cop/issues/223
* test_ros2action failure: https://github.com/ros2/build_cop/issues/222

#### Known flaky tests and recurring failures
 
* Pendulum tests fail on aarch64 with OpenSplice #133 
* Some builds fail to wipe the workspace due to processes from previous builds still running #161 
* gtest_multithreaded tests are flakey #180 
* tf2_ros_test_message_filter test is flakey #183 
* Linux test_component_manager fails on Linux repeated #184 
* Linux test_cli_remapping is flakey #194 
* Linux aarch64 test_parameter_server is flakey #201 
* Windows debug fails test_communications WString #203 
* Windows debug fails test_waitiable #204 
* Linux aarch64 test_lifecycle fails #205 
* rosbag2 test_play is flakey #210 
* Windows parameter tests are flakey #211 

#### Outstanding buildfarmer tasks

* Try to reduce the number of Windows failures due to not being able to delete files due to zombie processes from previous builds:
  * https://github.com/ros2/ci/pull/323

**Comment by jacobperron** [comment]
SROS 2 failure on Windows should be resolved by https://github.com/ros2/sros2/pull/155
