### ISSUE TITLE
rosindex job failure due to OOM

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#226]
Example: http://build.ros.org/job/doc_rosindex/84

```
/home/jenkins-agent/.bundle/gems/open4-1.3.4/lib/open4.rb:62:in `fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)
```

...Making things worse is that the job still shows green. Opened ros-infrastructure/rosindex#175 to address that.

**Comment by hidmic** [comment]
Did https://github.com/ros-infrastructure/rosindex/pull/175 solve the issue?

**Comment by tfoote** [comment]
It was resolved for a while, but we just saw this again: http://build.ros.org/job/doc_rosindex/171/

**Comment by tfoote** [comment]
It appears to be intermittent 174 passed: http://build.ros.org/job/doc_rosindex/174/

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
