### ISSUE TITLE
Build failure with OpenSplice on Windows due to MAXPATH

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#227]
Example: https://ci.ros2.org/view/nightly/job/nightly_win_extra_rmw_rel/440/consoleFull#console-section-302

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "action_tutorials_interfaces__rosidl_typesupport_opensplice_c__pyext.dir\Release\action_t.E18DE710.tlog\action_tutorials_interfaces__rosidl_typesupport_opensplice_c__pyext.lastbuildstate". Path: action_tutorials_interfaces__rosidl_typesupport_opensplice_c__pyext.dir\Release\action_t.E18DE710.tlog\action_tutorials_interfaces__rosidl_typesupport_opensplice_c__pyext.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. 
```

**Comment by sloretz** [comment]
@cottsay in the meeting today you mentioned [`\\?\` prefix'd to paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation) to workaround the 260 character limit. It looks like Windows 10 > 1607 has [a setting in the registry to remove the 260 character limit on all paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later). Do you think that's something we could add to our windows install instructions to solve this problem?

**Comment by cottsay** [comment]
It looks like that is part of MSFT's recommended solution for this issue: Microsoft/msbuild#53

We're already using MSBuild 16, so that may be enough. The key is:
```
HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled DWORD
```

I'll try it out on one of the Windows agents.

**Comment by cottsay** [comment]
Test build with the registry key set: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_win_extra_rmw_rel&build=445)](https://ci.ros2.org/job/nightly_win_extra_rmw_rel/445/)

**Comment by cottsay** [comment]
I made the change to the other two windows agents and rebooted them. We'll see how things go with the nightlies tonight.

**Comment by cottsay** [comment]
The suffering package appears to be back to good health, and I don't see any new test failures appearing after all of the nightlies ran with the flag set. If there are no objections and/or regressions by tomorrow morning, I'm going to close this issue.

**Comment by clalancette** [comment]
> The suffering package appears to be back to good health, and I don't see any new test failures appearing after all of the nightlies ran with the flag set. If there are no objections and/or regressions by tomorrow morning, I'm going to close this issue.

Just to check; did you update the installation instructions for Windows build-from-source users?

**Comment by cottsay** [comment]
> ...did you update the installation instructions...?

I did not - I'll put that on my list. Thanks.

**Comment by nuclearsandwich** [comment]
@cottsay I don't see a PR reference for install instructions, is this still in flight?

**Comment by rotu** [comment]
I think this might be the same issue as https://github.com/ros-tooling/libstatistics_collector/issues/53

Did we ever get to the bottom of this?

**Comment by cottsay** [comment]
> Did we ever get to the bottom of this?

Yup: https://github.com/ros2/build_farmer/issues/227#issuecomment-521022929

**Comment by rotu** [comment]
So what's needed to close this issue out?

**Comment by cottsay** [comment]
> So what's needed to close this issue out?

This: https://github.com/ros2/build_farmer/issues/227#issuecomment-521396583

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
