### ISSUE TITLE
Update chocolatey version on windows machines

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#23]
And also chocolatey packages versions as well.

This has proven to be a problem for users installing from "binaries" having a more recent version than us see https://github.com/ros2/ros2/issues/311

**Comment by wjwwood** [comment]
This is the process I am using on `eatable` to do the upgrades:

- `choco upgrade chocolatey` (new cmd afterwards)
- `choco version all` to see what can be upgraded
- `choco upgrade -y <list of things to upgrade>`
- download the latest versions of our custom chocolately packages from https://github.com/ros2/choco-packages/releases/tag/2017-04-04-1 and make sure they are installed in the same way
- in new cmd, make sure these programs still work and report the new version:
  - `python --version`
  - `cmake --version` (I had to update or re-add this one)
  - `git --version`
  - `cppcheck --version`
- do the java update if it is available
- build new version of python debug executables/libraries, see updated instructions:
  - https://github.com/ros2/ros2/wiki/Windows-Development-Setup#extra-stuff-for-debug-mode
- reboot and try CI / packaging jobs on the node to make sure things are still working

I used these copies of jobs (using the `windows_slave_testing` label) to see that eatable was working:

- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows_testing&build=2)](http://ci.ros2.org/job/ci_windows_testing/2/)
  - I'm tracking an issue with the cppcheck failures, but I think the other failures are not related:
    - https://github.com/ros2/ros2/issues/368
- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows_testing&build=1)](http://ci.ros2.org/job/packaging_windows_testing/1/)

I'll leave those jobs until we have tested all the windows machines.

I've changed `eatable`'s label back, but left it offline to prevent inconsistent jobs. I aim to do the rest of the machines tomorrow, all at once.

@clalancette FYI, these are the steps I took for the upgrade.

**Comment by mikaelarguedas** [comment]
Note: after upgrading python you will likely have a mismatch between the python interpreters' version. I don't know which version is on the machines but likely for some of them you will need an upgrade of the  python debug interpreter ( to match the python version provided by choco (3.6 I imagine)). To do so, follow the steps of the [Extra stuff to do in debug mode](https://github.com/ros2/ros2/wiki/Windows-Development-Setup#extra-stuff-for-debug-mode) section

**Comment by wjwwood** [comment]
Thanks for the reminder @mikaelarguedas I did this on eatable and I edited my post above to have that as part of the instructions. I also updated the wiki page for the Windows source install to use 3.6.1 which is what chocolately installs now (it was 3.6.0).

I also spent some time this morning trying this on my Windows desktop at home using VS2017 and ran into some issues. If I resolve them, I'll put some prebuilt debug binaries for Python for both VS2015 and VS2017, so they just have to be extracted and copied into the existing installation.

**Comment by wjwwood** [comment]
I duplicated the windows debug job to test out the new python debug stuff:

[![Build Status](http://ci.ros2.org/buildStatus/icon?job=nightly_win_deb_testing&build=1)](http://ci.ros2.org/job/nightly_win_deb_testing/1/)

**Comment by wjwwood** [comment]
The test windows deb nightly looks ok (in that it doesn't have obvious failures due to the new python debug build).

**Comment by wjwwood** [comment]
I've finished icecube, here are its test runs:

- Windows CI:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows_testing&build=3)](http://ci.ros2.org/job/ci_windows_testing/3/)
- Windows nightly debug:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=nightly_win_deb_testing&build=2)](http://ci.ros2.org/job/nightly_win_deb_testing/2/)
- Windows packaging:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows_testing&build=2)](http://ci.ros2.org/job/packaging_windows_testing/2/)

Once icecube passes those, I'll probably swap over (since we'll have two executors) and continue converting the other two machines (portable and windshield) in parallel with the cppcheck fixes and the nightlies if it runs long.

**Comment by wjwwood** [comment]
I've finished portable, here are its test runs:

- Windows CI:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows_testing&build=8)](http://ci.ros2.org/job/ci_windows_testing/8/)
- Windows nightly debug:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=nightly_win_deb_testing&build=4)](http://ci.ros2.org/job/nightly_win_deb_testing/4/)
- Windows packaging:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_windows_testing&build=3)](http://ci.ros2.org/job/packaging_windows_testing/3/)

**Comment by wjwwood** [comment]
portable is online again, but there is something weird going on with the java installation on windshield and I cannot keep it connected. Will look into it tomorrow.

**Comment by mikaelarguedas** [comment]
looks like https://github.com/ros2/build_cop/issues/22 was specific to windshield then and not a general windows machine problem. Thanks for pounding on all these updates!

**Comment by wjwwood** [comment]
Ok, all the machines have been updated and @clalancette fixed windshield's issue by reinstalling java.
