### ISSUE TITLE
test_communication failures in Debug only

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#230]
Example build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux_debug&build=1281)](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1281/)

**Comment by cottsay** [comment]
All of the failed tests are marked with `rclcpp__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp`.

**Comment by cottsay** [comment]
I've localized the regression to the Fast-RTPS update from v1.8.1 to tip.

Side-by-side builds:
Current ROS 2 development tip: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7884)](https://ci.ros2.org/job/ci_linux/7884/)
Same but with Fast-RTPS v1.8.1: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7883)](https://ci.ros2.org/job/ci_linux/7883/)

**Comment by cottsay** [comment]
This is the assert that is failing, highlighted in the PR that caused the regression: https://github.com/eProsima/Fast-RTPS/pull/646/files#diff-f74e057b5a456d6378532071b5e0f27bR338

**Comment by cottsay** [comment]
@dirk-thomas, any objections to pinning Fast-RTPS to the commit before the PR that caused the regression until it can be resolved? It would be good to get the packaging jobs green again, and give eProsima time to figure out what's going on with that assert.

**Comment by dirk-thomas** [comment]
It is weird that this only fails when the publisher is using `rclcpp` with `rmw_connext_cpp` and the subscriber is using `rclpy` with `rmw_fastrtps_cpp`. Instead of rolling back FastRTPS I would suggest to mark this specific test as skipped.

**Comment by cottsay** [comment]
> I would suggest to mark this specific test as skipped

Do you suggest this be done in the `test_communication` package itself, or via `--ctest-args` passed only if the build type is "Debug"?

**Comment by dirk-thomas** [comment]
The same as the other skipped tests in `test_communication` - in the `CMakeLists.txt` file.

**Comment by MiguelCompany** [comment]
This should have been fixed by eProsima/Fast-RTPS#678

**Comment by cottsay** [comment]
I re-enabled the tests in ros2/system_tests#383. We'll see how things do in the nightlies, and I'll close this out.
