### ISSUE TITLE
Upgrade mac and Windows CI hosts before Dashing Patch 3

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#234]
In order to produce usable binaries for Dashing Patch Release 3 this needs to be completed ahead of time, ideally with time to stabilize after any potential issues.

I've got the checklist I've used to do this at https://gist.github.com/nuclearsandwich/63ef5a2868ae8a7a6167283789e1a71e

Upgrade logs https://gist.github.com/nuclearsandwich/d4aa90b7c6532ff412fb13cb597bb9ab

**Comment by nuclearsandwich** [comment]
There is at least one known update that makes our MacOS binaries unusable on systems with up-to-date Homebrew installations: https://github.com/ros2/rosidl/issues/403

**Comment by nuclearsandwich** [comment]
As wjwwood did last week, starting with a canary host each

icecube :wind_chime: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=58)](https://ci.ros2.org/job/test_ci_windows/58/)
mini1 :apple: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=163)](https://ci.ros2.org/view/All/job/test_ci_osx/163/)

**Comment by nuclearsandwich** [comment]
Fresh builds

mini1 :apple: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=166)](https://ci.ros2.org/job/test_ci_osx/166/)
icecube :wind_chime: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=60)](https://ci.ros2.org/job/test_ci_windows/60/)

**Comment by j-rivero** [comment]
Ouch, mini1 is green. @nuclearsandwich do you want to launch it again to be sure it is ok?

**Comment by nuclearsandwich** [comment]
> Ouch, mini1 is green. @nuclearsandwich do you want to launch it again to be sure it is ok?

No actually I'm fine with that. I'm having trouble remembering if I rebooted mini1 before the first build.

**Comment by nuclearsandwich** [comment]
Dashing MacOS CI [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=167)](https://ci.ros2.org/job/test_ci_osx/167/)

There will probably be a few flake8 issues here which are due to a new error code. Other failures will need to be investigated.

**Comment by j-rivero** [comment]
> There will probably be a few flake8 issues here which are due to a new error code. Other failures will need to be investigated.

11 failures all related to flake8 and uncrustify.

**Comment by j-rivero** [comment]
portable [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=61)](https://ci.ros2.org/job/test_ci_windows/61/) [[update log](https://gist.github.com/j-rivero/1ef5b418282adebcffe562b3a15d96a2)]

**Comment by j-rivero** [comment]
mini2.local [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=169)](https://ci.ros2.org/job/test_ci_osx/169/) [[update log](https://gist.github.com/j-rivero/a02ed15efa460fba65ab9359e88af5be)]

**Comment by j-rivero** [comment]
mini3.local [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=170)](https://ci.ros2.org/job/test_ci_osx/170/) [[update log](https://gist.github.com/j-rivero/954e34619713600becfdeb60083656c4)]

There is one failing test in sros2 that does not seem related to uncrustify or flake8: https://ci.ros2.org/job/test_ci_osx/170/testReport/junit/sros2.test/test_policy_to_permissions/test_policy_to_permissions/

**Comment by nuclearsandwich** [comment]
@j-rivero has windshield been updated? If so I think this issue can be closed.

**Comment by j-rivero** [comment]
> @j-rivero has windshield been updated? If so I think this issue can be closed.

It wasn't. It is now: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=63)](https://ci.ros2.org/job/test_ci_windows/63/) [[update log](https://gist.github.com/j-rivero/ec3d6ef9b2fa0d6965b6b5a5dffb5f34)]

**Comment by nuclearsandwich** [comment]
Thanks!

**Comment by dirk-thomas** [comment]
It would be good to know from which version `cppcheck` was updated. Related to ros2/rmw_fastrtps#318.

**Comment by nuclearsandwich** [comment]
> It would be good to know from which version `cppcheck` was updated.

No cppcheck updates were available when I first started this process on 2019-08-28. As you can see from the upgrade log in the top post. @j-rivero's upgrade logs don't appear to include the from version for chocolatey (which is understandable as you have to do that work manually).

Looking at icecube cppcheck 1.88 is installed and cppcheck 1.89 [was released](https://sourceforge.net/p/cppcheck/news/2019/09/cppcheck-189/) 2019-09-01. So my educated guess is that the previous version was cppcheck 1.88.

Also @cottsay we should probably square up icecube with the other windows hosts.

**Comment by cottsay** [comment]
> Also @cottsay we should probably square up icecube with the other windows hosts.

After alignment with `portable`: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=67)](https://ci.ros2.org/job/test_ci_windows/67/) [[update log](https://gist.github.com/cottsay/b0bbf74577c98c456afb41b18faf20e0)]
