### ISSUE TITLE
Windows builds have failed due to internet connectivity loss

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#236]
Example builds:
- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=1495)](https://ci.ros2.org/view/packaging/job/packaging_windows/1495/)
- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_windows_debug&build=446)](https://ci.ros2.org/view/packaging/job/packaging_windows_debug/446/)

At this time, I believe that the flaky connection has resolved.

**Comment by dirk-thomas** [comment]
What is the action item for this ticket? It sounds like this is automatically resolved.

**Comment by dirk-thomas** [comment]
Also for the `nightly_win_deb` build it doesn't look to be related to an internet connection problem. The console output contains compiler errors which causes the build to fail.

**Comment by cottsay** [comment]
> What is the action item for this ticket? It sounds like this is automatically resolved.
1. Communicate to others (mainly @dirk-thomas) that I'm aware of the issue
2. Remind myself to follow-up by checking connectivity to the problematic URL from the affected host to verify that the problem was resolved (now that I'm done with my breakfast).

> the nightly_win_deb build it doesn't look to be related to an internet connection problem

You're right - I'll open another issue (#237).

**Comment by cottsay** [comment]
Both failures were on icecube, and I verified that the problematic URL could be accessed. I'm going to assume this was an intermittent connectivity issue that resolved on its own.
