### ISSUE TITLE
Regression in rcl_action tests

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#241]
Messages similar to:
```
Node name not found: ns='/', name='test_action_graph_old_node_name
```

Example failures:
- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux_release&build=1303)](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1303/)
- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux-aarch64_extra_rmw_release&build=477)](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_extra_rmw_release/477/)
- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_osx_debug&build=1379)](https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1379/)

**Comment by cottsay** [comment]
@ivanpauno, I believe that the patch series around ros2/ros2cli#322 regressed these tests. Could you please take a look?

**Comment by ivanpauno** [comment]
> @ivanpauno, I believe that the patch series around [ros2/ros2cli#322](https://github.com/ros2/ros2cli/pull/322) regressed these tests. Could you please take a look?

Yeah, I didn't run `rcl_action` graph test before merging.
It should be easy to fix.

**Comment by ivanpauno** [comment]
Fixed by https://github.com/ros2/rcl/pull/504.
@cottsay can you close the issue? I don't have write access here
