### ISSUE TITLE
Upgrade mac and Windows CI hosts

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#243]
In order to produce usable binaries for the next Dashing patch release this needs to be completed ahead of time, ideally with time to stabilize after any potential issues.

I've got the checklist I've used to do this at https://gist.github.com/nuclearsandwich/63ef5a2868ae8a7a6167283789e1a71e

Example upgrade logs: https://gist.github.com/nuclearsandwich/d4aa90b7c6532ff412fb13cb597bb9ab

**Comment by cottsay** [comment]
Prerequisite: ros/pluginlib#164

icecube [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=74)](https://ci.ros2.org/view/All/job/test_ci_windows/74/) [[update log](https://gist.github.com/cottsay/e05790579f7d65b71033856624ebbb24#file-icecube-local-md)]

**Comment by nuclearsandwich** [comment]
> Prerequisite: [ros/pluginlib#164](https://github.com/ros/pluginlib/pull/164)

https://github.com/ros/pluginlib/pull/166 applies the above change to ROS 2 mainline.

**Comment by cottsay** [comment]
portable [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=79)](https://ci.ros2.org/view/All/job/test_ci_windows/79/) [[update log](https://gist.github.com/cottsay/e05790579f7d65b71033856624ebbb24#file-portable-local-md)]

**Comment by cottsay** [comment]
windshield [![Build Status](https://ci.ros2.org/buildStatus/icon?job=test_ci_windows&build=80)](https://ci.ros2.org/view/All/job/test_ci_windows/80/) [[update log](https://gist.github.com/cottsay/e05790579f7d65b71033856624ebbb24#file-windshield-local-md)]

**Comment by nuclearsandwich** [comment]
mini1 is pretty much ready to go. There's one issue related to an updated version of graphviz https://github.com/ros-visualization/qt_gui_core/issues/190 and anything else is masked by issues also present on master.

**Comment by cottsay** [comment]
> mini1 is pretty much ready to go.

Awesome. Thank you! Could you publish an update log somewhere, so that we can reproduce the same results on the other minis?

**Comment by cottsay** [comment]
Okay, all three Windows hosts are up-to-date, less Python 3.8, which I think has a fairly high chance of regressing something. I'll do a test build with it updated and see how things go.

Is there anything else I should do to the macOS hosts to close out this ticket? Especially since mini1 is out of sync with the others?

**Comment by nuclearsandwich** [comment]
https://github.com/Homebrew/homebrew-core/pull/47792 or something similar will be needed to use the latest version of assimp via Homebrew. I don't think it's something we should apply locally ahead of Homebrew's review since anyone using our binaries will need to apply the same patch.

**Comment by nuclearsandwich** [comment]
assimp 5.0.1 was released four days ago which includes our bugfix and the bottle has now been rebuilt for it. So now our upgrades there are unblocked but of course everything else in Homebrew has moved so another upgrade round on the Mac hosts needs to be done. In the interest of not letting this ticket stay evergreen I'm going to close it and open another one for the Eloquent Patch 1 upgrades.
