### ISSUE TITLE
compiler warnings for ogre on Windows

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#245]
For a few days now, there have been compiler warnings on Windows:

https://ci.ros2.org/view/nightly/job/nightly_win_rel/1335/warnings43Result/

I mentioned it to @clalancette and he thinks it is related to https://github.com/ros2/rviz/commit/9ca3afceaf1e9dc2197b94c579768d4e1d608e4a, but he won't be able to get to it for a few days. I'm just opening this so it is tracked and people running CI can eliminate these warnings as an issue with their changes.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
