### ISSUE TITLE
All communication tests from fastrtps to connext are failing

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#246]
Regression first appeared in the 10/10 nightlies: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux_release&build=1327)](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1327/)

We didn't get nightlies on 10/9 due to a build-time regression, so I think the likely culprit is ros2/ros2#791.

@raquelalvarezbanos @MiguelCompany - could you guys please take a look?

**Comment by MiguelCompany** [comment]
@cottsay It seems we have an issue on the serialization of one QoS that may be causing these failures.
A fix is on the way in eProsima/Fast-RTPS#775

**Comment by nuclearsandwich** [comment]
https://github.com/ros2/ros2/pull/811 has resolved the test failures and the necessary change is also part of the 1.9.x branch which will be pinned by https://github.com/ros2/ros2/pull/814 until the Eloquent release.
