### ISSUE TITLE
Buildcop handoff 2017-05-30

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#25]
Notes from the previous week: https://github.com/ros2/build_cop/issues/21

Summary takeaway: We can pare down a few more flakes by resolving [some strange FastRTPS errors](http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/688/testReport/(root)/projectroot/test_tutorial_add_two_ints_server_add_two_ints_client_async__rmw_fastrtps_cpp/). I could discern no standout pattern with the other flakes.

#### Recent issues with work in progress

- [pip can't run with python debug interpreter due to SSL failures](https://github.com/ros2/ci/issues/77) was [error generating repository hashes causing jobs to fail](https://github.com/ros2/build_cop/issues/24).

#### Recent issues I didn't have time for

- [Update chocolatey and packages on Windows](https://github.com/ros2/build_cop/issues/23)
- [Configure eatable as a Windows 10 Machine](https://github.com/ros2/build_cop/issues/17) (deferred until necessary)

Feel free to close this at your leisure @wjwwood. Tag you're it. :boom:

**Comment by wjwwood** [comment]
Thanks. I'll see what I can do.

💫
😲
