### ISSUE TITLE
rclcpp multithreaded executor tests are failing

### ISSUE THREAD

**Issue by hidmic** [ros2/build_farmer#250]
See [here](https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1755/testReport/rclcpp/TestMultiThreadedExecutor/timer_over_take/) and [here](http://build.ros2.org/view/Eci/job/Eci__nightly-connext_ubuntu_bionic_amd64/134/testReport/rclcpp/TestMultiThreadedExecutor/timer_over_take/). It looks like a regression from https://github.com/ros2/rclcpp/pull/383 which seems odd to me. And of course I can't reproduce locally. 

CC @wjwwood, in case he remembers.

**Comment by wjwwood** [comment]
Maybe it is a regression, @mjcarroll pushed that one across the line. I don't remember the details at this point.

**Comment by mjcarroll** [comment]
It is, at the very least, far too timing sensitive.  I'm going to see if I can rework the test to make it less reliant on time.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
