### ISSUE TITLE
Timeouts downloading Freetype causing some Windows failures

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#252]
```
Building Custom Rule C:/J/workspace/nightly_win_extra_rmw_rel/ws/src/ros2/rviz/rviz_ogre_vendor/CMakeLists.txt
Performing download step (download, verify and extract) for 'freetype-2.8.1'
-- Downloading...
   dst='C:/J/workspace/nightly_win_extra_rmw_rel/ws/build/rviz_ogre_vendor/freetype-2.8.1-prefix/src/freetype2-VER-2-6-5.tar.gz'
   timeout='600 seconds'
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
-- Retrying...
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-2-6-5.tar.gz'
```

Failed builds
* https://ci.ros2.org/view/nightly/job/nightly_win_deb/1455/
* https://ci.ros2.org/view/nightly/job/nightly_win_deb/1447/
* https://ci.ros2.org/view/nightly/job/nightly_win_rep/1680/
* https://ci.ros2.org/view/nightly/job/nightly_win_extra_rmw_rel/565

Mostly opening for visibility. If this becomes a consistent or extreme problem we may have to explore hosting the binary separately. I could have sworn that due to similar problems we had a GitHub mirror of a sourceforge binary but I can't find hard evidence for it nor do I remember exactly which package it was.

This primarily affects windows since its the only platform where we are downloading and building freetype regularly in CI.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
