### ISSUE TITLE
ament_pep257 and flake8 failures with pydocstyle 5.0.0

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#255]
Many new pep257 errors have come with the release of [pydocstyle 5.0.0](https://github.com/PyCQA/pydocstyle/blob/master/docs/release_notes.rst#500---december-9th-2019).

All of these that I've looked at so far have been D401 related and this version of pydocstyle fixed an issue preventing that check from being run in all cases.

```
D401: First line should be in imperative mood; try rephrasing
```

Affected packages:
* ros2/launch https://github.com/ros2/launch/pull/362
  * launch
  * launch_testing
  * launch_xml
  * launch_yaml
* ros2/launch_ros https://github.com/ros2/launch_ros/pull/103
  * launch_ros
  * ros2launch
* quality_of_service_demo_py https://github.com/ros2/demos/pull/422
* rclpy https://github.com/ros2/rclpy/pull/480
* ros2topic https://github.com/ros2/ros2cli/pull/422
* rosidl_parser https://github.com/ros2/rosidl/pull/425
* micro-ROS/ros_tracing https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing/merge_requests/118
  * tracetools_launch
  * tracetools_test

**Comment by nuclearsandwich** [comment]
PR to address the changes in ros2_tracing, the others are visibule using GitHub cross-references. https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing/merge_requests/118

**Comment by nuclearsandwich** [comment]
~~CI for just Linux with the affected packages. The ros2_tracing repo is not included because I can't push branches there. [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8851)](https://ci.ros2.org/job/ci_linux/8851/)~~

I forgot to push a few branches so the CI above is incomplete.

**Comment by nuclearsandwich** [comment]
CI running linter tests for all above PRs except the ros_tracing merge request [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8854)](https://ci.ros2.org/job/ci_linux/8854/)

**Comment by wjwwood** [comment]
I don't know if it something we want to fix at all, but just so people are aware, this (and related changes) affect Dashing CI as well.

**Comment by nuclearsandwich** [comment]
> I don't know if it something we want to fix at all, but just so people are aware, this (and related changes) affect Dashing CI as well.

I've started running CI for non-latest rosdistros with linters off. We've generally held back on backporting linter only changes but if they're muddying CI and there's a willing backporter there is no reason not to.

**Comment by nuclearsandwich** [comment]
The last outstanding issue was resolved with https://github.com/ros2/ros2/pull/838
