### ISSUE TITLE
nightly_win_deb pytest failures

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#262]
There have been an uptick in test failures in the nightly_win_deb build, for example:  https://ci.ros2.org/view/nightly/job/nightly_win_deb/1510/testReport/

There is a consistent theme of `pytest.missing_result` failures.

A representative failure:

```
--- stderr: test_cli
01:58:24 CMake Warning at C:/J/workspace/nightly_win_deb/ws/install/share/ament_cmake_pytest/cmake/ament_add_pytest_test.cmake:77 (message):
01:58:24   The Python module 'pytest' was not found, pytests can not be run (e.g.  on
01:58:24   Ubuntu/Debian install the package 'python3-pytest')
01:58:24 Call Stack (most recent call first):
01:58:24   CMakeLists.txt:35 (ament_add_pytest_test)
01:58:24 
```

**Comment by mjcarroll** [comment]
`nightly_win_rel` seems not to be impacted.

**Comment by mjcarroll** [comment]
It looks like the root cause was pytest being unable to import `sqlite3` when using the Python debug interpreter.  I opted to reinstall `python3.7.5` on portable as an initial test, using the python installer as we now do in the container builds: https://github.com/ros2/ci/blob/94e2c543f0b373b59f9217eb3e65b3806fb05fb8/windows_docker_resources/Dockerfile.msvc2019#L44-L48

Before (run on windshield, which still has the issue): [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9226)](https://ci.ros2.org/job/ci_windows/9226/) (14 failures)
After (on portable): [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9227)](https://ci.ros2.org/job/ci_windows/9227/) (1 failure)

**Comment by mjcarroll** [comment]
I'm going to apply the same fix to windshield and icecube.

```
choco pin remove --name=python
choco pin remove --name=python3
choco uninstall python
choco uninstall python3
rmdir C:\Python37
```

Then reboot the system.

```
cd C:\
curl https://www.python.org/ftp/python/3.7.5/python-3.7.5-amd64.exe --output python-37.exe
C:\python-37.exe /quiet TargetDir=C:\Python37 PrepandPath=1 Include_debug=1 Include_symbols=1
```

**Comment by mjcarroll** [comment]
Testing on icecube: https://ci.ros2.org/job/ci_windows/9228/
Testing on windshield: https://ci.ros2.org/job/ci_windows/9231/

**Comment by mjcarroll** [comment]
This broke nighly windows packaging: https://ci.ros2.org/view/packaging/job/packaging_windows_debug/595/console

**Comment by mjcarroll** [comment]
One off to verify if those errors are gone: https://ci.ros2.org/job/ci_windows/9307/

**Comment by nuclearsandwich** [comment]
@mjcarroll's changes fixed the issue and I've opened https://github.com/ros2/ros2_documentation/pull/544 to update our installation instructions to match.
