### ISSUE TITLE
Failure in test_subscriber_terminates_in_a_finite_amount_of_time

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#264]
Since https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1456/ (Feb 11), we've had multiple failing tests that look like:

```
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/build/test_communication/test_publisher_subscriber__rclcpp__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp_Debug.py", line 66, in test_subscriber_terminates_in_a_finite_amount_of_time
    proc_info.assertWaitForShutdown(process=subscriber_process, timeout=10)
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/proc_info_handler.py", line 144, in assertWaitForShutdown
    assert success, "Timed out waiting for process '{}' to finish".format(process)
AssertionError: Timed out waiting for process '<launch.actions.execute_process.ExecuteProcess object at 0x7fdff1cfd5f8>' to finish
```

**Comment by clalancette** [comment]
Looking more closely, all of the failures are between `rmw_connext_cpp` and `rmw_fastrtps_cpp`.  It seems to happen with both `rclcpp` and `rclpy` tests, so is probably something lower-level than that.

**Comment by clalancette** [comment]
Side note: this is a useful command for checking out all repositories before a certain date:

```
find . -type d -iname .git | while read dir ; do top=$(dirname $dir) ; pushd $top ; git checkout `git rev-list -n 1 --first-parent --before="2020-02-09" HEAD` ; popd ; done
```

**Comment by dirk-thomas** [comment]
Have you tried if the tests pass when using an older commit of FastRTPS?

**Comment by clalancette** [comment]
> Have you tried if the tests pass when using an older commit of FastRTPS?

Not yet, will try that soon.

**Comment by clalancette** [comment]
* All latest code, with pinned Fast-RTPS: https://ci.ros2.org/job/ci_linux/9339/ (expected success)
* Code from February 10th, with Fast-RTPS only upgraded to latest: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1460 (expected failure)

**Comment by clalancette** [comment]
https://github.com/eProsima/Fast-RTPS/issues/1014

I'm going to run another job or two to see if I can narrow down the commit.

We also have the memory corruption problem in https://github.com/eProsima/Fast-RTPS/pull/1013 to worry about.  However, I'm still going to suggest that we pin Fast-RTPS for the overnight jobs for now, and we can deal with the other problem when eProsima merges it.

**Comment by clalancette** [comment]
https://ci.ros2.org/job/ci_linux/9340/ (Fast-RTPS pinned to https://github.com/eProsima/Fast-RTPS/commit/c3131012337ea3939cae9cb2be4931a641558477)

**Comment by clalancette** [comment]
> https://ci.ros2.org/job/ci_linux/9340/ (Fast-RTPS pinned to [eProsima/Fast-RTPS@c313101](https://github.com/eProsima/Fast-RTPS/commit/c3131012337ea3939cae9cb2be4931a641558477))

This causes the failure, so that commit is the culprit.

**Comment by dirk-thomas** [comment]
> This causes the failure, so that commit is the culprit.

Which is eProsima/Fast-RTPS#1003.

**Comment by clalancette** [comment]
The nightlies from last night didn't have this particular failure, so things are improved.

There's also a potential fix for this problem pending in Fast-RTPS: https://github.com/eProsima/Fast-RTPS/pull/1015

I've kicked off a job to test if it fixes the issue in https://ci.ros2.org/job/ci_linux/9344/

**Comment by clalancette** [comment]
All right, in theory all of the problems have been sorted in Fast-RTPS.  I'm kicking off a job on all platforms on the newest Fast-RTPS; assuming that passes, we can unpin it.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9374)](http://ci.ros2.org/job/ci_linux/9374/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5059)](http://ci.ros2.org/job/ci_linux-aarch64/5059/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7676)](http://ci.ros2.org/job/ci_osx/7676/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9290)](http://ci.ros2.org/job/ci_windows/9290/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=156)](http://ci.ros2.org/job/ci_windows-container/156/)

**Comment by clalancette** [comment]
All right, looks like the latest Fast-RTPS worked for test_communication, at least.  I'm going to kick off one more full build of the system on Linux, and assuming that is green I'll propose a PR to unpin Fast-RTPS to get the latest fixes.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9387)](http://ci.ros2.org/job/ci_linux/9387/)

**Comment by clalancette** [comment]
All right, some test failures, but they seem like the same ones from the nightly: https://ci.ros2.org/view/nightly/job/nightly_linux_release/1449 .  PR upcoming to unpin Fast-RTPS.
