### ISSUE TITLE
actionlib_msgs deprecation warning when building ros1_bridge

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#267]
## Affected jobs

* https://ci.ros2.org/view/packaging/job/packaging_linux
* https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64
* https://ci.ros2.org/view/packaging/job/packaging_linux-armhf

Introduced by https://github.com/ros2/common_interfaces/pull/75

The warning is [generated in ament_cmake](https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/cmake/core/templates/nameConfig.cmake.in#L22-L30) which handles the `deprecated` state from package.xml.

Possible resolutions:

* Un-deprecate the package
* Update ament_cmake to allow a consuming package to skip the warning. CMake has a separate DEPRECATION message class which may be useful there https://cmake.org/cmake/help/v3.0/command/message.html
* Suppress this specific deprecation warning in ROS 2 CI configurations as we do for unused variable warnings.

Suppressing the deprecation in situ in ros1_bridge's CMakeLists.txt holds the most appeal to me. How practical that is depends on how we design the ament_cmake change.

**Comment by jacobperron** [comment]
+1 for the second option, switching to a DEPRECATION message in ament_cmake. I'll look into how straight forward this can be ignored in the consuming package (ros1_bridge).

**Comment by dirk-thomas** [comment]
I don't think that we want to blindly hide all CMake deprecation messages. So :-1: for doing that.

I prefer option ~3~ 2: `ros1_bridge` sets a flag to explicitly skip the deprecation message from `actionlib_msgs` and only that message.

**Comment by dirk-thomas** [comment]
I don't think that we want to blindly hide all CMake deprecation messages. So :-1: for doing that.

I prefer option 3: `ros1_bridge` sets a flag to explicitly skip the deprecation message from `actionlib_msgs`.

**Comment by jacobperron** [comment]
> I prefer option 3 2: ros1_bridge sets a flag to explicitly skip the deprecation message from actionlib_msgs and only that message.

This is what I was thinking; I guess it should be possible.

Edit: err, but potentially skipping all deprecation warnings coming from actionlib_msgs, not just the one coming from ament_cmake.

**Comment by nuclearsandwich** [comment]
Thanks @jacobperron :tada:
