### ISSUE TITLE
mass failures due to setuptools bug

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#27]
See: https://github.com/pypa/setuptools/issues/1042

Basically all our Linux jobs are failing, here is a sample:

- http://ci.ros2.org/view/packaging/job/packaging_linux/697/console
- http://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/62/console
- http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/96/console
- http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/58/console
- http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/58/console
- http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/399/console
- http://ci.ros2.org/view/nightly/job/nightly_linux_debug/472/console
- http://ci.ros2.org/view/nightly/job/nightly_linux_release/461/console
- http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/671/console

I think the best thing to do is to wait for a new setuptools release. They are aware of it and should fix it asap since it's affecting so many. If it is not fixed in the morning I'll try to find a way to version lock us to setuptools < 36 in all the right places.

**Comment by clalancette** [comment]
FYI, it looks like setuptools fixed the issue.  I did a quick rebuild of nightly_linux_debug just to check, and it does install setuptools 36.0.1, and seems to be proceeding: http://ci.ros2.org/view/nightly/job/nightly_linux_debug/473

I'm not sure if we want to manually trigger all of the rest, or just wait until tonight to let them all run.

**Comment by wjwwood** [comment]
Thanks, I might run one or two today but I'll probably just let them run again tonight.
