### ISSUE TITLE
Many tests not grouped by project

### ISSUE THREAD

**Issue by rotu** [ros2/build_farmer#271]
A bunch of CI tests are showing up under `projectroot` as opposed to associated with the project they are part of:

https://ci.ros2.org/job/ci_linux/10180/testReport/junit/(root)/projectroot/

for example, cppcheck_rosidl_typesupport_c, which seems to be split between here:
https://ci.ros2.org/job/ci_linux/10180/testReport/junit/(root)/projectroot/cppcheck_rosidl_typesupport_c_4/

and here:
https://ci.ros2.org/job/ci_linux/10180/testReport/junit/rosidl_typesupport_c/cppcheck/

**Comment by hidmic** [comment]
I believe the duplication is introduced by `CTest` XML output being picked up, as well as that generated by the testing tool itself (e.g. `pytest`, `gtest`, etc.). Do you recall why we pick up `CTest` output @dirk-thomas?

**Comment by dirk-thomas** [comment]
> Do you recall why we pick up `CTest` output

Because both xml result files provide sometimes different information and are therefore helpful in triaging.

**Comment by hidmic** [comment]
I see. Since the Jenkins plugin is unable to correlate both inputs we _could_ try aggregate them (in some yet to be defined way). It's a tricky task though, each testing tool often leverages the jUnit format in its own peculiar way.

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
