### ISSUE TITLE
ros-foxy-desktop missing in ros2-testing because of spurious `joy` failure

### ISSUE THREAD

**Issue by emersonknapp** [ros2/build_farmer#275]
See https://build.ros2.org/job/Fbin_uF64__joy__ubuntu_focal_amd64__binary/60/console 

```
07:12:20 Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libmount.a: no space left on device
```

The dependency on this build is blocking https://build.ros2.org/job/Fbin_uF64__desktop__ubuntu_focal_amd64__binary - so http://packages.ros.org/ros2-testing/ubuntu/dists/focal/main/binary-amd64/Packages is missing `ros-foxy-desktop`

**Comment by clalancette** [comment]
I do believe that this transient error went away on the buildfarm.  And it looks like `ros-foxy-desktop` is available again.  So I'll close this out, but feel free to reopen if you think this is in error.
