### ISSUE TITLE
All ci_windows builds failing - can't find uncrustify executable

### ISSUE THREAD

**Issue by emersonknapp** [ros2/build_farmer#276]
For example: https://ci.ros2.org/job/ci_windows/13399/testReport/junit/(root)/rosbag2_transport/uncrustify_xunit_missing_result/

```
Error Message
The test did not generate a result file:

Could not find 'uncrustify' executable
```

**Comment by clalancette** [comment]
This was fixed by https://github.com/ament/uncrustify_vendor/pull/16
