### ISSUE TITLE
image demo not working on eatable

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#3]
Since eatable has been turned back on it is failing the image demo tests.
@clalancette to give context about what has been done on the node and its reactivation

CI failing tests:
http://ci.ros2.org/job/ci_windows/2534/
http://ci.ros2.org/job/ci_windows/2555/
list of builds here: http://ci.ros2.org/computer/windows_slave_eatable/builds

**Comment by clalancette** [comment]
I just took eatable offline.  I added additional information to the logbook, but essentially:

- This is our only Windows 8.1 machine.
- It is randomly failing some tests that work fine on our other Windows (10) machines.
- It probably needs an update to RTI Connext, and maybe some other software.

So we should probably just leave it offline until someone has time to debug the problems, and/or declare Windows 8 unsupported.

**Comment by dhood** [comment]
sorry to be late to the party, I only just found this repo. my notification settings are fixed now.

Last time I saw [that output for image demo tests](http://ci.ros2.org/job/ci_windows/2555/testReport/junit/(root)/test_showimage_cam2image__rmw_connext_cpp_Release/test_reliable_qos/) on windows buildfarm machines, it was resolved by setting the opencv path (entry 16 in the logbook). The other test failures seem to just be flaky tests, right?

I sense that there is more context here around disabling eatable, so I am trying to get the info on paper before we forget about this.

**Comment by nuclearsandwich** [comment]
> sorry to be late to the party, I only just found this repo. my notification settings are fixed now.

No worries, we actually recommended folks unwatch this repo with the intention that only current the buildcopfarmer _needs_ to be watching this space.

**Comment by mikaelarguedas** [comment]
> It probably needs an update to RTI Connext, and maybe some other software

It may not have a patched version of connext that would lead to randomly failing generated messages when running in multithreaded

There is also the more global question of: "do we target Windows8.1 support?" if yes we may want another windows8.1 machine and create different jobs for those. If not this should be upgraded to be another Windows 10 node

**Comment by dirk-thomas** [comment]
This will be obsolete with eatable being offline and scheduled to be reprovisioned with Windows 10 (see #17).
