### ISSUE TITLE
nightly windows machine failing to find OpenSSL

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#31]
It's hard for me to tell if this is an issue with Fast-RTPS's CMake or something else (because of the parallel interleaving).

```
07:33:35 CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
07:33:35   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
07:33:35   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
07:33:35   OPENSSL_INCLUDE_DIR)
07:33:35 Call Stack (most recent call first):
07:33:35   C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
07:33:35   C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
07:33:35   CMakeLists.txt:211 (find_package)
```

-- http://ci.ros2.org/job/nightly_win_rep/687/consoleFull

@mikaelarguedas do you have any idea?

**Comment by wjwwood** [comment]
Another data point: http://ci.ros2.org/job/nightly_win_rep/688/console

Both times seems to be on eatable. Was it just not configured correctly?

**Comment by mikaelarguedas** [comment]
Very likely, eatable was offline when I installed OpenSSL on the windows
machines.

**Comment by mikaelarguedas** [comment]
Sorry I missed the first mention yesterday. I installed openssl 1.0.2L on eatble and define the environment variable accordingly. Maybe a restart would be needed for those to be taken into account. I leave it to you discretion @wjwwood to restart the windows machines because they may want to download half of the internet in updates during the next restart

**Comment by mikaelarguedas** [comment]
I believe thisi can be closed now, the last eatable build passed http://ci.ros2.org/view/nightly/job/nightly_win_rep/689/

**Comment by wjwwood** [comment]
Sounds good to me. We can just keep an eye out on it.
