### ISSUE TITLE
nightly_linux_repeated had different failures from the night before

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#35]
http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/691/

It had both new failures, and didn't have some of the failures from the night before, suggesting that some of the tests were either fixed or flakey.  Hoping for the former, here are the new failures:

- projectroot.test_demo_cyclic_pipeline__rmw_connext_cpp
- projectroot.test_messages_c__rmw_connext_cpp
- projectroot.test_tf2_geometry_msgs
- projectroot.test_showimage_cam2image__rmw_fastrtps_cpp
- TfGeometry.Frame
- TfGeometry.Vector
- TfGeometry.Point
- TestMessagesFixture.test_dynamicarraynested
- test_showimage_cam2image__rmw_fastrtps_cpp_.test_reliable_qos
- test_pendulum__rmw_connext_cpp.test_executable
- intra_process_demo.test_demo_cyclic_pipeline__rmw_connext_cpp.xunit.missing_result
- test_services_cpp__rmw_fastrtps_cpp_.test_services_cpp

**Comment by dirk-thomas** [comment]
Please include a link to the job you are referring to. Also I am not sure there is much benefit to list tests which are known to be flaky. Imo it just decreases the signal-to-noise ratio.
