### ISSUE TITLE
upgrade dependencies on macOS ci.ros2.org build nodes

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#38]
This is process I am using.

Once for the whole upgrade process:

- duplicate ci_osx, changing the label to have a `_testing` suffix

(I'm only testing `ci_osx` because macOS doesn't do anything different for debug builds or packaging builds)

- take the node offline
- change the label by adding a `_testing` suffix
- vnc in to see if there are updates (open `App Store` app), do them if there are
- ssh or vnc in to terminal and do `brew update` (this updated brew's definitions, like `apt update`)
- do `brew outdated` to see what can be upgraded
- pin the version of tinyxml2 for now `brew pin tinyxml2`
  - if you accidentally already installed 5.0.0, you can install 4.0.1 with this: `brew uninstall tinyxml2; brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/196dee239038f34b2bbe8ca2f183ec78a5a53ce2/Formula/tinyxml2.rb && brew pin tinyxml2`
  - see: https://github.com/eProsima/Fast-RTPS/issues/113 and https://github.com/eProsima/Fast-RTPS/pull/114
- either do `brew upgrade` to upgrade all or do selective ones with `brew upgrade [[[pkg1] pkg2] ...]`
- update to Java 8 update 131 (by downloading from java website via safari via vnc)
- reboot
- bring the node back online (with the adjusted label in place) and run the ci_osx_testing job (ensuring that it gets on the target machine by disabling the other machines on that label if any)
- if the test passes, change the label back (remove the `_testing` suffix)

**Comment by wjwwood** [comment]
dosa looks good:

- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx_testing&build=3)](http://ci.ros2.org/job/ci_osx_testing/3/)

I'm going to swap dosa over as the new machine and upgrade the other two as soon as I see a good opportunity.

**Comment by wjwwood** [comment]
mini2 is good:

- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx_testing&build=4)](http://ci.ros2.org/job/ci_osx_testing/4/)

**Comment by wjwwood** [comment]
mini1 is good:

- [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx_testing&build=5)](http://ci.ros2.org/job/ci_osx_testing/5/)

**Comment by mikaelarguedas** [comment]
:tada: thanks @wjwwood
