### ISSUE TITLE
unpin and upgrade tinyxml2 to version 5.0.0 on macOS

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#39]
We've currently pinned the version of tinyxml2 to 4.0.1 on our macOS build machines, but we should update them to the latest version once Fast-RTPS integrates my patch (or a similar patch) into their master:

https://github.com/eProsima/Fast-RTPS/pull/114

Also the instructions should be updated too:

- https://github.com/ros2/ros2/wiki/OSX-Development-Setup
- https://github.com/ros2/ros2/wiki/OSX-Install-Binary

See also: https://github.com/ros2/build_cop/issues/38#issue-237995936

**Comment by mikaelarguedas** [comment]
I think this is ready to be addressed now that https://github.com/eProsima/Fast-RTPS/pull/114 has been merged

**Comment by wjwwood** [comment]
Yeah, I'll take this task. I'm checking things out on my laptop first.

**Comment by mikaelarguedas** [comment]
:+1: thanks!

**Comment by wjwwood** [comment]
Should be good to go now.
