### ISSUE TITLE
Build farmer/cop handoff 2017-08-15

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#44]
__Farmer:__
- Pending tasks:
  - update java on OSX and Windows nodes (https://github.com/ros2/build_cop/issues/43)
  - update packages on master and linux2:
    - may fix https://github.com/ros2/build_cop/issues/30 now that docker 17.05 available on trusty, I updated [linux3](https://gist.github.com/mikaelarguedas/739a4826ac69463d8f5caf5f165af00e) and havent seen the docker failure since
  - investigate packet.net node failure (https://github.com/ros2/build_cop/issues/42)
- Nice to have: Try VS2017 and assess if we can migrate Windows nodes to it
- Recurrent tasks:
    - make system updates on MacOS and Windows machines
    - upgrade eatable to windows 10
    - keep chocolatey packages up to date on Windows nodes

__Cop:__
- Outstanding issues:
  - New failing test: time operators (tracked [here](https://github.com/ros2/rclcpp/issues/357))
  - rcl_get_node_names became flakier than before on all platforms (example [here](http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/775/testReport/junit/(root)/projectroot/test_get_node_names__rmw_fastrtps_cpp/)), mainly tracked [here](https://github.com/ros2/ros2/issues/371). Still confused of why it started failing much more often recently
  - rcl_test_wait / test_timeout became flakier on Windows (has always been flaky but now fail on most CI not only repeated nightlies)

- Job status:
  - Packaging jobs: green
  - Nightlies: green except time operators. 
  - Repeated: all yellow, <15 failing tests per night per platform :tada:. Still 58 different tests failed in the last 5 days (script [here](https://raw.githubusercontent.com/mikaelarguedas/ci/mikael/flaky_test_script/aggregate_flaky_tests.py))

**Comment by wjwwood** [comment]
Thanks @mikaelarguedas! I'm going to close this as these issues are tracked separately, but it's definitely useful to get started.
