### ISSUE TITLE
rtiddsgen sometimes segfaults on nightlies for macOS

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#46]
I've seen this at least twice now, where `rtiddsgen` will segfault:

```
08:00:44 subprocess.CalledProcessError: Command '['/Applications/rti_connext_dds-5.2.3/bin/rtiddsgen_server', '-I', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/nav_msgs/rosidl_generator_dds_idl', '-I', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/install/builtin_interfaces/share', '-I', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/install/geometry_msgs/share', '-I', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/install/std_msgs/share', '-d', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/nav_msgs/rosidl_typesupport_connext_cpp/nav_msgs/srv/dds_connext', '-language', 'C++', '-namespace', '-update', 'typefiles', '-unboundedSupport', '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/nav_msgs/rosidl_generator_dds_idl/nav_msgs/srv/dds_connext/GetMap_Request_.idl']' died with <Signals.SIGSEGV: 11>.
```

I'm not sure why it's happening, perhaps it is running out of memory due to parallel?

http://ci.ros2.org/job/nightly_osx_release/570/consoleFull

**Comment by mikaelarguedas** [comment]
I think that's a duplicate of https://github.com/ros2/build_cop/issues/40

I'm not sure its a memory issue because that happens on my beefy desktop sporadically as well. I think it's an issue in rtiddsgen that doesnt handle several instances properly but I have no idea why exactly.

For what ist worth I havent seen the issue a single time on connext 5.3. Maybe it's a known bug they fixed, could be worth having a look at their release notes

**Comment by wjwwood** [comment]
I saw #40, and I don't think it is the same error.

**Comment by mikaelarguedas** [comment]
Yeah looks like the linux one is different, The one on OSX on the referenced job is the same though. Maybe I shouldn't have put the linux error on the same issue, sorry for the confusion

**Comment by wjwwood** [comment]
No actually you're right, I was basing that of of the error you pasted into the comments about linux. I think the comment on #40 about linux should be a separate issue and this is a duplicate of #40.

**Comment by wjwwood** [comment]
What you said.

**Comment by wjwwood** [comment]
Closing in favor of https://github.com/ros2/build_cop/issues/40
