### ISSUE TITLE
Move jenkins workspace from C:/ to D:/ on eatable.local

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#51]
Jenkins refused to allow eatable to come online because it's C:/ drive only had 7 GB left of free space. Deleting the contents of the workspace allows it to come online.

Eatable's C:/ drive is only 111GB in size and at the moment has about 30GB of free space, but it has a much larger D:/ drive with 600 GB of free space. Maybe the jenkins folder should be moved to the D:/ drive.

**Comment by sloretz** [comment]
This seems like a good thing to do when updating eatable to windows 10

**Comment by mikaelarguedas** [comment]
Is it the same physical drive ? If yes, maybe we can just resize partitions and keep the same install layout as the other nodes?

**Comment by mikaelarguedas** [comment]
Apparently C: and D: are [different physical drives](https://github.com/ros2/build_cop/issues/17#issuecomment-371485294) so we would need to reinstall on the other drive if we want to leverage the additional space. At that point we may want to compare performance in case the smaller drive is an SSD and the bigger one an HDD.

**Comment by clalancette** [comment]
@ros2/team What's the status of eatable?  It's not currently in the buildfarm, do we plan to add it at some point?  Or should we close this out?

**Comment by nuclearsandwich** [comment]
Eatable is semi-reserved as a machine to test chef configuration management for Windows machines. This can either get closed if we want it out of the way or it can get assigned to me to make sure I leave a capability for it when setting up the configuration management.

**Comment by clalancette** [comment]
I'm going to close this out, since eatable is no longer part of the build farm and not reachable at the moment.  Feel free to reopen if and when eatable comes back online.
