### ISSUE TITLE
Every nightly job jas had a failing test since september 22

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#55]
Seems there is a common set of test failures across all jobs. Every single nightly job has had a test failure since september 22.

http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/212/testReport/
http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/173/testReport/
http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/517/testReport/
http://ci.ros2.org/view/nightly/job/nightly_linux_debug/591/testReport/
http://ci.ros2.org/view/nightly/job/nightly_linux_release/576/testReport/
http://ci.ros2.org/view/nightly/job/nightly_osx_debug/597/testReport/
http://ci.ros2.org/view/nightly/job/nightly_osx_release/600/testReport/
http://ci.ros2.org/view/nightly/job/nightly_turtlebot-demo_linux-aarch64_release/73/testReport/
http://ci.ros2.org/view/nightly/job/nightly_turtlebot-demo_linux_release/72/testReport/
http://ci.ros2.org/view/nightly/job/nightly_win_deb/614/testReport/
http://ci.ros2.org/view/nightly/job/nightly_win_rel/565/testReport/
http://ci.ros2.org/view/nightly/job/nightly_win_rep/797/testReport/

They all appear to have the same 16 failed tests

```
    projectroot.test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_0
    projectroot.test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_1
    projectroot.test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_2
    projectroot.test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_3
    projectroot.test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_0
    projectroot.test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_1
    projectroot.test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_2
    projectroot.test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_3
    projectroot.test_composition__rmw_fastrtps_cpp
    test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_0_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_1_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_2_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_3_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_2_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_1_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__DynamicArrayNested__rmw_fastrtps_cpp__secure_comm_3_Release.test_secure_publisher_subscriber
    test_secure_publisher_subscriber__Empty__rmw_fastrtps_cpp__secure_comm_0_Release.test_secure_publisher_subscriber
    composition.test_composition__rmw_fastrtps_cpp.xunit.missing_result
```

@mikaelarguedas  mentioned it might be related to fast-RTPS switching to OpenSSL 1.1.0

**Comment by mikaelarguedas** [comment]
Yeah I think it comes from https://github.com/eProsima/Fast-RTPS/commit/fdb758181c36705f73dcae45f7280eddce9b34bf investigating now

**Comment by mikaelarguedas** [comment]
Ticketed [here](https://github.com/eProsima/Fast-RTPS/issues/149)

**Comment by sloretz** [comment]
eProsima/Fast-RTPS#149

**Comment by mikaelarguedas** [comment]
This had been fixed in https://github.com/eProsima/Fast-RTPS/commit/3f238281c5e856e767edf42b5f3037d8edd1a34a
And CI passed:
 * Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3273)](http://ci.ros2.org/job/ci_linux/3273/)

**Comment by dhood** [comment]
there are some warnings on windows that I've asked them to address https://github.com/eProsima/Fast-RTPS/issues/149#issuecomment-332945394

**Comment by mikaelarguedas** [comment]
warning have been fixed http://ci.ros2.org/job/ci_windows/3327/
