### ISSUE TITLE
Build farmer/cop handoff 2017-09-28

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#56]
Previous handoff ros2/build_cop#48

__Farmer:__
- ~~In progress tasks ( I'll keep working on these rather than handing them off ):~~
  - ~~Revive linux 3~~ **Done**
    - ~~Linux 3 disappeared, I've almost finished setting up an instance to replace it~~
  - ~~Revive dosa~~ **Done**
    - ~~Dosa would not stop disconnecting from jenkins every 20ish minutes. Reinstalling macOS in hopes that it fixes the problem.~~
- Pending tasks:
  - update java on Windows nodes (#43)
  - update packages on master and linux2 (hopefully solving #30)
  - investigate packet.net node failure (#42)
  - upgrade eatable to windows 10
- Nice to have:
  - Try VS2017 and assess if we can migrate Windows nodes to it
- Recurring tasks:
    - system and package (brew/chocolatey) updates on MacOS and Windows machines
      - mini1 and mini2 were just updated, windows machines were updated a couple weeks ago before beta3

__Cop:__
- Outstanding issues:
  - (old, have not confirmed if this is still an issue) rcl_get_node_names became flakier than before on all platforms (example [here](http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/775/testReport/junit/(root)/projectroot/test_get_node_names__rmw_fastrtps_cpp/)) see ros2/ros2#371
  - (old, have not confirmed if this is still an issue)rcl_test_wait / test_timeout became flakier on Windows (has always been flaky but now fail on most CI not only repeated nightlies)
  - All jobs have 16 security related tests failing (#55)

- Job status:
  - Packaging jobs: green
  - Nightlies: yellow
  - Repeated: yellow

flaky test script [here](https://raw.githubusercontent.com/mikaelarguedas/ci/mikael/flaky_test_script/aggregate_flaky_tests.py)

**Comment by mikaelarguedas** [comment]
Note: next nightlies should be green now that the Fast-RTPS issue has been resolved.
ci.ros2.org doesn't display the description of the current buildfarmer and buildfarmer log on the default page anymore but on the nightly view

**Comment by dhood** [comment]
Update on Dosa: after a couple of extra steps after @sloretz upgraded it to High Sierra (https://github.com/ros2/ros2/issues/409, https://github.com/ros2/build_cop/issues/58), it's back online, but slower than before. This standard CI job took 3.5hrs: http://ci.ros2.org/job/ci_osx/2634/ (test failure unrelated)
Of the 3.5h of that job: 2.5h build, 1h test vs [this job on Dosa before upgrade](http://ci.ros2.org/job/nightly_osx_release/567/) that was 1h build 45min test, so mostly it's the build step that has slowed (there wasn't any workspace config delay).

**Comment by dhood** [comment]
running a build through the terminal on the machine as opposed to through the jenkins UI, it still takes 2.5 hrs, with or without the jenkins slave agent running.

**Comment by nuclearsandwich** [comment]
Closing old handoff issues.
