### ISSUE TITLE
Need to install libpcl development libraries on OSX from homebrew

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#6]
ros2/pcl_conversions#1 needs the libpcl development libraries installed to work, so we need to do this on the OSX build farm machines.

**Comment by nuclearsandwich** [comment]
libpcl installed on mini2. Temporarily bringing down the other nodes to force a rebuild of http://ci.ros2.org/job/ci_osx/1928/ on mini2.

**Comment by nuclearsandwich** [comment]
libpcl installed on the mac machines but builds are still failing due to CMake config. More info in https://github.com/ros2/pcl_conversions/pull/1#issuecomment-294863435

I expect this will be resolved by updating the source repo but leaving this open until that's confirmed.

**Comment by dirk-thomas** [comment]
> Temporarily bringing down the other nodes to force a rebuild of http://ci.ros2.org/job/ci_osx/1928/ on mini2.

You don't have to disable nodes for this. The better approach is to temporarily use a different node label (e.g. the node name) to the job.

**Comment by clalancette** [comment]
All right.  So it seems like libpcl on OSX doesn't have the cmake files, for whatever reason.  I'm not quite sure how to proceed here, I'll do some searching and see if I find anything.

**Comment by clalancette** [comment]
http://pointclouds.org/documentation/tutorials/installing_homebrew.php seems to suggest we'll get the development files if we install from that "tap", instead of from the "bottle" (ug, the naming is too cute).  We may have to try that.

**Comment by dirk-thomas** [comment]
@clalancette @nuclearsandwich Any update on this?

**Comment by clalancette** [comment]
We haven't gotten back to it yet.

**Comment by mikaelarguedas** [comment]
If there is no near future plan for porting the turtlebot2_demo (or other PCL based demos) to MacOS I think we should close this. We can reopen a ticket with all the dependencies that need to be ported to the other platforms when we need them. @nuclearsandwich @clalancette thoughts ?

**Comment by clalancette** [comment]
Yeah, I agree.  I'll close this out for now.
