### ISSUE TITLE
Dosa python packages updated

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#62]
This is a heads up for the build cop; while doing some testing on dosa today, I accidentally updated the versions of python installed via brew from 2.7.13_1 -> 2.7.14 and python3 from 3.6.2 -> 3.6.3.  I'm running a test right now to see if this matters (http://ci.ros2.org/job/chris-osx/1); if it doesn't, then we can either update the other OSX nodes, try to downgrade dosa (which I don't know how to do right now), or just close this ticket.  Since it is my mistake, I'll clean it up, I just want to know what we should do to move forward.

**Comment by dhood** [comment]
there was a fragile workaround to get testing to work with SIP enabled that a python upgrade would have broken (see https://github.com/ros2/build_cop/issues/61). I'll fix it; it's not really your fault because the machine shouldn't be left in this fragile state.

**Comment by clalancette** [comment]
I'm going to close this out since Dosa has been reinstalled, and this no longer applies.
