### ISSUE TITLE
Updating buildfarm linux hosts

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#66]
In order to address issues like #30 and to try and keep the x86 hosts on roughly the same Docker track as the arm64 hosts, also because it's responsible.

I started this morning with linux 2. I'll get linux 3 (which was deployed only recently and running Ubuntu Xenial) next and determine a time when it is suitable to update the Jenkins master.

**Comment by nuclearsandwich** [comment]
cc current build farmer @clalancette

**Comment by nuclearsandwich** [comment]
There isn't enough space left available on ci.ros2.org to make a backup of the Jenkins home directory before updating that machine.

`/var/lib/jenkins` is currently at 447G of a 985G volume. It's also just about double the size of build.ros.org's jenkins home directory during the migration.

Are we committed to keeping all this build data or is it more a matter of setting appropriate log rotation for ci.ros2.org.

**Comment by clalancette** [comment]
It seems to me like we don't really need to keep all of that data; some number of builds from the past (say, 30) would suffice.  I'll let others chime in, though, to see if there is a particular reason to keep them all.

**Comment by dirk-thomas** [comment]
I think all the history is valuable. It happens that you want look back at older builds linked from various tickets to check / compare / review stuff.

Since the system has still 500 GB left I don't see why we should consider deleting any history.

I don't understand why you need to duplicate the content before the update? What kind of update are you referring to? Just for updating the master I don't think cloning the whole build history is necessary.

**Comment by mikaelarguedas** [comment]
>  I'll let others chime in, though, to see if there is a particular reason to keep them all.

@clalancette Please @ the team for us to be notified we're suppose to chime in.

> Since the system has still 500 GB left I don't see why we should consider deleting any history.

:+1: just yesterday I had to go look at builds from 2 years ago. I'd be in favor of keeping everything as long as we can.

**Comment by nuclearsandwich** [comment]
> I don't understand why you need to duplicate the content before the update? What kind of update are you referring to? Just for updating the master I don't think cloning the whole build history is necessary.

Of course I don't foresee any issues. I just want to install available updates and reboot the machine. But I've also been doing sysadmin work long enough to know that you don't do anything you can't afford to undo. If the update goes terribly horribly awfully wrong, or if amazon decides to terminate this instance, it's entirely possible we could lose all of this data anyway. Hence asking 

1) if we need a backup? __Answer:__ we do if we actually care about this data, no matter what.
2) Do we need to backup all of it?

**Comment by nuclearsandwich** [comment]
Linux hosts were all re-provisioned and are running up-to-date Ubuntu 16.04 and the build history has been migrated with them.

They are not automatically kept up-to-date but we are iterating toward that point. Based on the comments here about the team's value of build history, we should look at creating backups for the build history in case something happens to the host which destroys or corrupts the history data.
