### ISSUE TITLE
flake8 started failing overnight on most python packages

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#67]
Overnight, it looks like all of the nightly jobs started going yellow (example: http://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/261).  It looks like there is a new flake8 warning that is occurring on nearly every piece of python code in ROS2; that warning looks like this:

```
./ros2cli/plugin_system.py:21:1: I202 Additional newline in a section of imports.
from ros2cli.entry_points import load_entry_points
^

./ros2cli/node/daemon.py:26:1: I202 Additional newline in a section of imports.
from xmlrpc.client import ProtocolError
^

2     I202 Additional newline in a section of imports.
```

In all cases that I looked at, the code in question looks something like:

```
from nose.tools import assert_raises

from rosidl_parser import Type
```

If I get rid of that newline, then the warning goes away, but I actually find the newline helpful to separate out groups of imports.  @ros2/team what is your opinion?  Should I fix all of these violations, or should we disable the `I202` warning?

**Comment by mikaelarguedas** [comment]
Are these violations fixed if you place a comment between sections?
```
# PackageA group
import packageA
# PackageB group
import packageB.foo
import packageB.bar
```

I think it makes sense to have a space between system imports and user-installed package imports.
I'm fine either way for blank lines between use installed packages. If the comment happens to fix it and forces us to document our import group that may be a good compromise. But I'm fine disabling the warning if we think it's not worth the overhead of adding these comments

**Comment by dhood** [comment]
My vote would be to disable it and keep the style as is

**Comment by clalancette** [comment]
> Are these violations fixed if you place a comment between sections?

I just gave that a whirl locally, and the answer is no, that doesn't fix it, we still get the violation.

I'm going to go ahead and come up with a patch to disable this warning for now.  If others have dissenting opinion, just let me know.  Thanks :).

**Comment by dirk-thomas** [comment]
> I think it makes sense to have a space between system imports and user-installed package imports.

The problem is that both blocks contain "user defined" packages in the case of the warning. `nose` is in the same boat as `rosidl_parser` here. Since there is no good way to apply the policy to "non ROS" packages but not to ROS packages I think disabling it is the best option for now.

**Comment by mikaelarguedas** [comment]
Yes I agree with that, I'm just saying that I understand why flake8 complains when we add spaces between non system imports (our packages or third party installed by us). I'm fine disabling the warning especially given that the suggested alternative doesnt fix it

**Comment by clalancette** [comment]
Both PRs needed to get this resolved are merged, so I'm going to close this out.
