### ISSUE TITLE
Linux packaging jobs failing

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#68]
Looks like there's an issue building `ros1_bridge` lately, e.g. http://ci.ros2.org/job/packaging_linux/877
```
/usr/bin/ld: CMakeFiles/dynamic_bridge.dir/src/dynamic_bridge.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/dynamic_bridge.dir/build.make:330: recipe for target 'dynamic_bridge' failed
```

**Comment by clalancette** [comment]
Yeah, I've been looking into it, but I haven't been able to figure out what is going wrong yet.  Thanks for opening up the issue to track it.

**Comment by clalancette** [comment]
As a brief follow-up, I now know the proximate cause of the problem.  Looking closely at the link line when trying to build `dynamic_bridge`, there are no boost libraries listed at all.  Looking even closer, this only happens with the version of roscpp in Kinetic testing (version 1.12.11).  If we use an older version of roscpp (1.12.7 is what is in stable), then things work fine.  I'm going to go a bit deeper and see what has changed there to make this fail.

**Comment by mikaelarguedas** [comment]
Why are we using the testing ROS1 repo for our jobs ?
I mean the issue will happen when that version of roscpp makes it to the main repo so that's good to look into it, I'm just curious why we would use the "unstable" ROS 1 packages for testing ROS 2

**Comment by dhood** [comment]
I suppose it makes sense for us to test our own things as much as possible even if they're from a different "project"

**Comment by clalancette** [comment]
> Why are we using the testing ROS1 repo for our jobs ?
> I mean the issue will happen when that version of roscpp makes it to the main repo so that's good to look into it, I'm just curious why we would use the "unstable" ROS 1 packages for testing ROS 2

Yeah, I was wondering the same thing.  The short-term fix would be to switch back to stable, but as you say we'll have to fix it anyway.  I don't really have a strong feeling, so if we want to have the packaging jobs switch back to stable, I'm happy to do that.  Either way, I'm going to look into roscpp to see what changed.

**Comment by mikaelarguedas** [comment]
If that was the motivation, I disagree with it.
If we rely on a ROS 1 package (that we may not maintain ourselves) we won't provide nightly binaries to ROS 2 users until the maintainer of the ROS 1 package eventually fixes it. I don't think ROS 2 users should pay the price of unstable ROS 1 packages not released to the main repo yet.
Maybe at the time we needed something that was only in testing but long term I believe we should use main.

**Comment by clalancette** [comment]
Going back in the history on https://github.com/ros2/ci, it looks like the ROS1 repository has *always* been testing, right from the very beginning.  It looks like William did this initially; @wjwwood is there any particular reason for us to use testing rather than the "released" ROS1 repositories?

**Comment by clalancette** [comment]
All right, I also see why this is failing with the newer version of `roscpp`.  What's happening is that the new version of `roscpp` has changed `/opt/ros/kinetic/lib/pkgconfig/roscpp.pc` from having `-l:/usr/lib/x86_64-linux-gnu/libboost_system.so` to having just `/usr/lib/x86_64-linux-gnu/libboost_system.so`.  This actually doesn't come from `roscpp` itself, but rather from this catkin commit: https://github.com/ros/catkin/commit/6ede6d49d39855aa91d0141ebd65a701261ea346 .  In turn, the code in ros1_bridge depended on that old `-l:` behavior, here: https://github.com/ros2/ros1_bridge/blob/master/cmake/find_ros1_package.cmake#L31; in particular, things without a `-l` are *not* part of `ros1_roscpp_LIBRARIES`, so they never get put into the link line.  Thus, the good news is that we just need a fix in https://github.com/ros2/ros1_bridge, though it may be slightly tricky to get the correct set of libraries in there.  I'll work on that next.
