### ISSUE TITLE
Need to install libpcl-dev in the docker containers

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#7]
To get ros2/pcl_conversions#1 working, we need to have libpcl-dev installed inside of the Linux docker containers.

**Comment by nuclearsandwich** [comment]
Since this is targetting the turtlebot demo you should be able to update the dependencies by changing [this line](https://github.com/ros2/ci/blob/ac7ec89e398d0afcc879dc38840dad7bc264e3dc/linux_docker_resources/Dockerfile#L89).

**Comment by nuclearsandwich** [comment]
In progress with https://github.com/ros2/ci/pull/57

**Comment by dhood** [comment]
closing now that https://github.com/ros2/ci/pull/54 has been merged

**Comment by clalancette** [comment]
Thanks!
