### ISSUE TITLE
[Windows] Hang in vcs import

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#71]
I remember we had this issue in the past in qemu but that's the first time I see this on windows:
http://ci.ros2.org/job/ci_windows/3761/console

**Comment by nuclearsandwich** [comment]
Closing this for now as we've had 300 CI jobs  a couple months of nightlies run without incident. If we start hitting this again we can aggregate failed builds associated with this here in order to investigate.
