### ISSUE TITLE
Install Qt5 on MacOS and Windows hosts for rviz2

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#75]
Linux hosts are served by [forthcoming PR] since they use docker containers rather than rely on installed packages of the base host.

Question for @wjwwood: Is there any subset of Qt5 I should install on via Homebrew and the Windows installer or should I just go for everything?

**Comment by wjwwood** [comment]
@nuclearsandwich on macOS, I just need `brew install qt`, though since qt still doesn't get linked by default (see: https://github.com/Homebrew/homebrew-core/issues/8392#issuecomment-334328367 by our own @scpeters) I have to set the `CMAKE_PREFIX_PATH` explicitly. That might need to go in the `ci` repo's logic for now...

On Windows, I just installed the qt libraries for `msvc2015` and `msvc2017` 64-bit. By default it installs a lot more, which would be fine, but I wanted to know what the minimum set was.

**Comment by wjwwood** [comment]
Oh, also, on Windows you have to set the `Qt5_DIR` env variable to get cmake to find qt on your system. For what ever reason it doesn't find it with the cmake provided module without that. Not sure if that belongs in the ci repo's logic or if that should just be set as a global env variable on the machines themselves.

**Comment by nuclearsandwich** [comment]
> CMAKE_PREFIX_PATH explicitly. That might need to go in the ci repo's logic for now...

Yeah, that will probably need to go with ros2/ci#116 in the batch script for now.

> Oh, also, on Windows you have to set the Qt5_DIR env variable to get cmake to find qt on your system. For what ever reason it doesn't find it with the cmake provided module without that. Not sure if that belongs in the ci repo's logic or if that should just be set as a global env variable on the machines themselves.

We could export that or set the CMake registry variables like the chocolatey packages do [(example)](https://github.com/ros2/choco-packages/blob/55963f1832184fce21340e7197ab41a6e0e5338d/package/tinyxml-usestl/tools/tools/chocolateyinstall.ps1#L19)

**Comment by wjwwood** [comment]
> > CMAKE_PREFIX_PATH explicitly. That might need to go in the ci repo's logic for now...

> Yeah, that will probably need to go with ros2/ci#116 in the batch script for now.

See: https://github.com/ros2/ci/pull/117/commits/f737b668e7f33b514ae5c65c08cb3fcf4a067131

**Comment by wjwwood** [comment]
I am going to install Qt5 on all the macOS build machines. Since I'm disabling rviz on Windows for now, the pr in ros2/ci should be sufficient otherwise.

**Comment by wjwwood** [comment]
I'll wait for the jobs to finish and take the machines off-line one at a time to do this. (switching to slack for the rest of the updates on this)

**Comment by wjwwood** [comment]
Looks like the macOS machines also need freetype, not sure why that's not required on Linux (I believe ogre builds it). I'm going to wait until this round passes/fails but I probably will add that package to the macOS machines afterwards (I'll also update the google doc @mikaelarguedas).

Note to self:

- Update instructions for source/binary installation on Linux and macOS

**Comment by mikaelarguedas** [comment]
Closing this as the machines have been updated and the instructions for OSX have been updated.
@wjwwood Feel free to reopen if there is any action item that hasn't been addressed
