### ISSUE TITLE
Buildcop handoff 2017-04-18

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#8]
@nuclearsandwich is passing the build 👮 👩‍🌾 hat to @dhood 

### Open issues on handoff day

- ⛏ #3 Image demo not working on eatable (unstarted)
- 🔧 #6 Need libpcl on MacOS (in progress)
- 🔧 #7 Need libpcl-dev in Docker containers (in progress)
- 🐛 https://github.com/ros2/ci/issues/56 Daily invalidation of Dockerfiles isn't working

### Notable recent changes

- Jenkins agent on MacOS nodes mini1 and mini2 is supervised by launchd.
- NTP installed on Linux machines.

**Comment by nuclearsandwich** [comment]
Just a quick note that I updated the internal docs to specify how to start and stop the launchd-managed Jenkins agents. I was still figuring out how to invoke Dosa in a completely blocking manner so it can also be supervised. It might be as simple as `javaws -wait "${HOME}/Desktop/iforgetthefilename.jnlp"` but it needs to be tested as running with no options kept the javaws process in the foreground but the actual agent process didn't exit when the javaws process did.

**Comment by dhood** [comment]
thanks @nuclearsandwich !

**Comment by dirk-thomas** [comment]
I will close this handoff issue since the individual tasks are ticketed separately.
