### ISSUE TITLE
test_composition__rmw_fastrtps_cpp failing across almost all jobs

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#80]
Between Jan 4th and 5th the test `test_composition__rmw_fastrtps_cpp` started failing on all nightly builds (except the release one). While the test was flaky before and known to fail on the repeated jobs it looks like something has changed which makes it much more "reliable" to fail.

**Comment by sloretz** [comment]
On my machine the following tests within `test_composition__rmw_fastrtps_cpp` hang, all others pass if these are commented out.

* test_api_pubsub_composition
* test_api_srv_composition
* test_api_srv_composition_client_first

Possibly coincidence, but the failing tests are also the only tests that use the `api_composition` and `api_composition_cli` executables.

Possibly related to ros2/demos#159

**Comment by mikaelarguedas** [comment]
:+1: that matches what I saw when testing those during my last build cop shift, only these 3 tests hang sometimes making the test flaky on most platforms.

**Comment by dhood** [comment]
in the past I've noticed the regex for those tests sometimes doesn't match the outputs if the outputs come in a different order (this causes a test to hang waiting for the regex to match). Perhaps simplifying the regex/making it robust to order changes would help these tests

**Comment by dirk-thomas** [comment]
I am closing this since ros2/launch#68 addressed the problem described here. ros2/demos#159 will continue to track the remaining test failures.
