### ISSUE TITLE
mini2, icecube cannot run pytest with pytest-cov failures

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#83]
This is in regards to fails like this:

http://ci.ros2.org/view/nightly/job/nightly_osx_release/755/testReport/osrf_pycommon.tests/test_code_format/test_flake8/

This is the error:

```
E       AssertionError: 'out 1' not found in 'Failed to import the site module\nTraceback (most recent call last):\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 544, in <module>\n    main()\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 530, in main\n    known_paths = addusersitepackages(known_paths)\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 282, in addusersitepackages\n    user_site = getusersitepackages()\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 258, in getusersitepackages\n    user_base = getuserbase() # this will also set USER_BASE\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 248, in getuserbase\n    USER_BASE = get_config_var(\'userbase\')\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 601, in get_config_var\n    return get_config_vars().get(name)\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 580, in get_config_vars\n    import _osx_support\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_osx_support.py", line 4, in <module>\n    import re\n  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>\n    class RegexFlag(enum.IntFlag):\nAttributeError: module \'enum\' has no attribute \'IntFlag\'\n'
```

I tried uninstall `enum34` (which was installed), which fixed some of the cases but didn't fix them all, according to this SO post:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

However, when the virtualenv is setup again `enum34` is brought in a again by `flake8-import-order`.

I opened an issue against them to see if it can be fixed upstream:

https://github.com/PyCQA/flake8-import-order/issues/149

I guess we'll have to wait for an upstream fix.

**Comment by sloretz** [comment]
Also showed up on [`windows_slave_icecube`](http://ci.ros2.org/view/nightly/job/nightly_win_rel/725/#showFailuresLink) in these tests

```
osrf_pycommon.tests.test_code_format.test_flake8
ros2srv.test.test_cli.test_cli
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_combined
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_combined_unbuffered
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_unbuffered
ros2msg.test.test_cli.test_cli
ros2pkg.test.test_cli.test_cli
```

**Comment by wjwwood** [comment]
Update, this might be a problem with `setuptools`?

https://github.com/PyCQA/flake8-import-order/issues/149#issuecomment-367106730

**Comment by wjwwood** [comment]
Looks like it: https://github.com/pypa/setuptools/issues/1072#issuecomment-367109149

**Comment by nuclearsandwich** [comment]
Is there a workaround for this we could employ? Perhaps uninstalling the enum34 package in the venv after resolving deps?

**Comment by wjwwood** [comment]
That might work. I was hoping upstream would move on the issue sooner.

**Comment by wjwwood** [comment]
Looks like it's fixed now, closing with this now clean (for this problem at least) CI job:

https://ci.ros2.org/job/ci_osx/3343/

**Comment by mikaelarguedas** [comment]
This error still appears on the [windows nightlies](https://ci.ros2.org/view/nightly/job/nightly_win_rel/744/#showFailuresLink). Though it's using the same version of setuptools and flake8-import order as the MacOS job linked above.

I'll reopen this for book keeping, feel free to close again if not appropriate

**Comment by sloretz** [comment]
In the windows nightly log before installing packages the output of pip freeze shows enum34 is installed on icecube

```
07:30:25 ==> C:\Python36\python.exe -m pip freeze
07:30:26 asttokens==1.1.7
07:30:26 attrs==17.4.0
07:30:26 colorama==0.3.9
07:30:26 coverage==4.5.1
07:30:26 empy==3.3.2
07:30:26 enum34==1.1.6
07:30:26 flake8==3.5.0
07:30:26 flake8-blind-except==0.1.1
07:30:26 flake8-builtins==1.0.post0
07:30:26 flake8-class-newline==1.6.0
07:30:26 flake8-comprehensions==1.4.1
07:30:26 flake8-deprecated==1.3
07:30:26 flake8-docstrings==1.3.0
07:30:26 flake8-import-order==0.17.1
07:30:26 flake8-polyfill==1.0.2
07:30:26 flake8-quotes==0.14.0
07:30:26 mccabe==0.6.1
07:30:26 mock==2.0.0
07:30:26 nose==1.3.7
07:30:26 pbr==3.1.1
07:30:26 pep8==1.7.1
07:30:26 pluggy==0.6.0
07:30:26 py==1.5.2
07:30:26 pycodestyle==2.3.1
07:30:26 pydocstyle==2.1.1
07:30:26 pyflakes==1.6.0
07:30:26 pyparsing==2.2.0
07:30:26 pytest==3.4.2
07:30:26 pytest-cov==2.5.1
07:30:26 pytest-runner==4.0
07:30:26 PyYAML==3.12
07:30:26 sip==4.19.6
07:30:26 six==1.11.0
07:30:26 snowballstemmer==1.2.1
07:30:26 trollius==2.1
07:30:26 vcstool==0.1.33
```

Looks like it is installed system wide on icecube. I'll try uninstalling it now that the wheel for flake8-import-order has been fixed.

```
C:\User\osrf>python -m pip show enum34
Name: enum34
Version: 1.1.6
...
Location: c:\python36\lib\site-packages
...
```

**Comment by sloretz** [comment]
I uninstalled enum34 from icecube, portable, and windshield. I'll close this if the next CI windows runs without these test failures

**Comment by wjwwood** [comment]
Sorry it might need to be explicitly removed on the machines, I didn't think to check that. But at least it shouldn't be reinstalled anymore.
