### ISSUE TITLE
osx nightly stuck  waiting for rviz_ogre_vendor

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#88]
https://ci.ros2.org/job/nightly_osx_repeated/1015/console appears to have gottent stuck. The final symptom is it printing the following message for a few hours.

```
08:49:35 [Waiting for: rviz_ogre_vendor]
08:50:35 [Waiting for: rviz_ogre_vendor]
08:51:35 [Waiting for: rviz_ogre_vendor]
08:52:35 [Waiting for: rviz_ogre_vendor]
08:53:35 [Waiting for: rviz_ogre_vendor]
08:54:35 [Waiting for: rviz_ogre_vendor]
...
17:28:39 [Waiting for: rviz_ogre_vendor]
17:29:39 [Waiting for: rviz_ogre_vendor]
17:30:39 [Waiting for: rviz_ogre_vendor]
17:31:39 [Waiting for: rviz_ogre_vendor]
17:32:39 [Waiting for: rviz_ogre_vendor]
17:33:39 [Waiting for: rviz_ogre_vendor]
```

**Comment by nuclearsandwich** [comment]
This has happened a few times before. The one that I saw was stuck on rviz_common: https://ci.ros2.org/job/nightly_osx_release/741/console

This is a near duplicate of #77 which is aggregating hangs like these. It's notable that all of the reported cases are on dosa.

**Comment by nuclearsandwich** [comment]
The next time we see a hang like this, we should do some investigation into process state before killing it. The Activity Monitor utility in MacOS can tell us what processes are running and the files they have open as a start. We should be able to use dtruss to examine processes in more detail.

**Comment by sloretz** [comment]
Closing as a duplicate of #77
