### ISSUE TITLE
OSX test_get_node_names failed to due to api_composition

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#89]
A test in rcl failed on one of the nightly OSX jobs. It looks like the api_composition test didn't get completely cleaned up, and one of it's nodes threw of this test result. It's possible this is a bug in either [ros2/launch](https://github.com/ros2/launch) or [ros2/demos](https://github.com/ros2/demos), but I'm making an issue here until I know more.

[nightly_osx_release #772](https://ci.ros2.org/job/nightly_osx_release/772)
```
projectroot.test_get_node_names__rmw_connext_cpp
rcl.TestGetNodeNames__rmw_connext_cpp.test_rcl_get_node_names
```

```
-- run_test.py: extra environment variables:
 - RMW_IMPLEMENTATION=rmw_connext_cpp
 - DYLD_INSERT_LIBRARIES=/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test/memory_tools/librcl_memory_tools_interpose.dylib
-- run_test.py: extra environment variables to append:
 - DYLD_LIBRARY_PATH+=/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl
 - DYLD_LIBRARY_PATH+=/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test/memory_tools
-- run_test.py: invoking following command in '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/src/ros2/rcl/rcl':
 - /Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test/test_get_node_names__rmw_connext_cpp --gtest_output=xml:/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test_results/rcl/test_get_node_names__rmw_connext_cpp.gtest.xml
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestGetNodeNames__rmw_connext_cpp
[ RUN      ] TestGetNodeNames__rmw_connext_cpp.test_rcl_get_node_names
test_get_node_names__rmw_connext_cpp(50932,0x7fff92170340) malloc: starting memory checking...
/Users/osrf/jenkins/workspace/nightly_osx_release/ws/src/ros2/rcl/rcl/test/rcl/test_get_node_names.cpp:91: Failure
Expected equality of these values:
  size_t(2)
    Which is: 2
  node_names.size
    Which is: 3
[test_rcl_get_node_names]: Found node names:
node1
api_composition
node2

/Users/osrf/jenkins/workspace/nightly_osx_release/ws/src/ros2/rcl/rcl/test/rcl/test_get_node_names.cpp:93: Failure
Expected equality of these values:
  0
  strcmp(node2_name, node_names.data[1])
    Which is: 13
test_get_node_names__rmw_connext_cpp(50932,0x7fff92170340) malloc: stopping memory checking...
REDAWorker_enterExclusiveArea:worker U00007fff92170340 deadlock risk: cannot enter 0x7fb330427d60 of level 40 from level 40
REDACursor_modifyReadWriteArea:!enter worker (U00007fff92170340)'s exclusive area
PRESPsService_removeRemoteEndpoint:!modify pres psRemoteWriter
REDAWorker_enterExclusiveArea:worker U00007fff92170340 deadlock risk: cannot enter 0x7fb330427d60 of level 40 from level 40
REDACursor_modifyReadWriteArea:!enter worker (U00007fff92170340)'s exclusive area
PRESPsService_removeRemoteEndpoint:!modify pres psRemoteReader
REDAWorker_enterExclusiveArea:worker U00007fff92170340 deadlock risk: cannot enter 0x7fb3320179a0 of level 40 from level 40
REDACursor_modifyReadWriteArea:!enter worker (U00007fff92170340)'s exclusive area
PRESPsService_removeRemoteEndpoint:!modify pres psRemoteWriter
REDAWorker_enterExclusiveArea:worker U00007fff92170340 deadlock risk: cannot enter 0x7fb3320179a0 of level 40 from level 40
REDACursor_modifyReadWriteArea:!enter worker (U00007fff92170340)'s exclusive area
PRESPsService_removeRemoteEndpoint:!modify pres psRemoteReader
[  FAILED  ] TestGetNodeNames__rmw_connext_cpp.test_rcl_get_node_names (7481 ms)
[----------] 1 test from TestGetNodeNames__rmw_connext_cpp (7481 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (7481 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestGetNodeNames__rmw_connext_cpp.test_rcl_get_node_names

 1 FAILED TEST
-- run_test.py: return code 1
-- run_test.py: inject classname prefix into gtest result file '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test_results/rcl/test_get_node_names__rmw_connext_cpp.gtest.xml'
-- run_test.py: verify result file '/Users/osrf/jenkins/workspace/nightly_osx_release/ws/build/rcl/test_results/rcl/test_get_node_names__rmw_connext_cpp.gtest.xml'
```

**Comment by sloretz** [comment]
Hmm it does not look like extra node names did not come from the nightly itself. The test `test_get_node_names` test runs between 8:41:13 and 8:51:49. The composition tests don't start until 8:54:41. The extra node name in the output is sometimes `api_composition` and sometimes `api_composition_cli`, so it looks a lot like a composition test.

Possibly some machine in the office is using the same domain id as dosa?

**Comment by sloretz** [comment]
Looks like dosa used `ROS_DOMAIN_ID=111` from the log. Wireshark filter `rtps.domain_id==111` shows mini1 is currently using that same domain id.

**Comment by sloretz** [comment]
Looks like [111 is the default domain id given to OSX CI nodes](https://github.com/ros2/ci/blob/35b86c8492ea5e80c0653bedfa403d3ab4717acc/ros2_batch_job/osx_batch/__init__.py#L40-L41). Recent build logs showed mini1, mini2, and dosa were all using 111. I added an environment variable ROS_DOMAIN_ID to those nodes via the jenkins UI to set to values from the domain id spreadsheet. Looks like mini1 is using the new value in a CI job now, so I'll close this issue.

**Comment by nuclearsandwich** [comment]
@sloretz can you verify that dosa and mini2 are also using the configured ids. With the default agent.jar jenkins runner environment variable changes were not picked up without a process restart. I would have expected the swarm client to behave the same way.

**Comment by sloretz** [comment]
@nuclearsandwich I can confirm mini1 and mini2 report the new environment variable value in a ci_osx job  without restarting the agent process. I don't know if dosa picked it up because it's assigned domain id is the same as the default. If you'd like I can temporarily change the id used by dosa to see if it got the value

**Comment by nuclearsandwich** [comment]
> If you'd like I can temporarily change the id used by dosa to see if it got the value

I think it would actually be more valuable to permanently re-assign Dosa off of the default value but I'm not entirely familiar with the domain id and since we maintain the tables internally maybe it doesn't matter.

**Comment by sloretz** [comment]
I can move dosa do a different id. Alternatively since using the default means a risk of overlapping with another machine on the default maybe CI should error if ROS_DOMAIN_ID is unset rather than providing a default.

**Comment by dirk-thomas** [comment]
:+1: for erroring out if the domain id is not set. Better fail visibly than collide silently.

**Comment by nuclearsandwich** [comment]
> +1 for erroring out if the domain id is not set. Better fail visibly than collide silently.

I like this approach as well!
