### ISSUE TITLE
Dosa won't boot (macOS could not be installed on this computer)

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#90]
I restarted dosa (thinking it was the easiest way to get the jenkins agent process to restart and use some new environment variables), but dosa refuses to boot. It shows a dialog where the only option is to restart, and restarting brings up the same dialog.

typed by hand:
```
macOS could not be installed on your computer

The path /System/installation/Packages/OSInstall.mpkg appears to be missing or damaged.
Quit the installer to restart your computer and try again.
[restart]
```

**Comment by dhood** [comment]
poor dosa :disappointed:

**Comment by sloretz** [comment]
@scpeters showed me how to run a hardware test. Both the short test and extended test report no issues found on dosa.

**Comment by nuclearsandwich** [comment]
Oof. Most of the googling about that issue says it pops up during the install process. Did you and scpeters try any of the other generic macos fiddling like nvram and smc resets?

**Comment by dhood** [comment]
Dosa has been retired and will be replaced by mini3
