### ISSUE TITLE
Python3 not found on mini1

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#91]
Build farmer logbook doesn't mention any changes to mini1 since January (launchd supervision but it's been running builds fine since then). @ros2/team Has anyone made any changes to mini1 lately?

https://ci.ros2.org/job/nightly_osx_repeated/1025/console

```
# BEGIN SECTION: Run script
11:55:08 + /usr/local/bin/python3 -u run_ros2_batch.py --do-venv --force-ansi-color --workspace-path /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated --connext --disable-connext-dynamic --fastrtps --repo-file-url https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos --isolated --ament-build-args --parallel --cmake-args -DSECURITY=ON --- -- --ament-test-args --retest-until-fail 20 --ctest-args -LE linter --- --
11:55:08 /var/folders/3w/m29y0l2j4zd5pzhv82kn4w780000gn/T/jenkins2874869095105224804.sh: line 84: /usr/local/bin/python3: No such file or directory
11:55:08 Build step 'Execute shell' marked build as failure
```

**Comment by sloretz** [comment]
hmm I thought I added an entry for adding .profile to mini1, mini2, and dosa yesterday, but I don't see it in the log. Adding the only recent change to mini1 I'm aware of.

**Comment by mikaelarguedas** [comment]
I did ran `brew update` on mini1 to get the list of outdated packages for the release. I think that's the only thing that happened on the machine since yesterday.
I upgraded python as we needed the current version anyway. It seems to have fixed the issue [![Build Status](http://ci.ros2.org/buildStatus/icon?job=test_ci_osx&build=50)](https://ci.ros2.org/job/test_ci_osx/50).

I'll add an entry to the logbook once I'm done updating the other packages on that machine.

**Comment by dhood** [comment]
phew, thanks!

**Comment by mikaelarguedas** [comment]
Additional context: Apparently the issue is that by updating the brew database, brew found out that the python3 formula was removed (in favor of the python formulae that now points to python3) and deciding to unlink python3.

Console output below:
```
==> Deleted Formulae
python3 ✔                  root@5                     ruby@1.9
clozure-cl                 ros/deps/console_bridge    ruby@2.1
go@1.6                     ros/deps/urdfdom           tomcat@8.0
go@1.7                     ros/deps/urdfdom_headers
==> Processing python3 formula rename to python
==> Unlinking python3
==> Temporarily unlinking python
==> Moving python3 versions to /usr/local/Cellar/python
==> Relinking python
Warning: python is outdated!
To avoid broken installations, as soon as possible please run:
  brew upgrade
Or, if you're OK with a less reliable fix:
  brew upgrade python
```
