### ISSUE TITLE
build farmer handoff 2018-03-07

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#92]
- Newer issues:
  - Composition tests failing consistently on arm #86
  - dosa won't boot #90
- Older chores
  - #84 
  - Switch to VS2017 once Connext provides public binaries (ros2/ci#122)
  - Configure eatable now that it is running Windows 10 (#17)

**Comment by dhood** [comment]
superseded by https://github.com/ros2/build_cop/issues/107
