### ISSUE TITLE
Connext: Automatic participant index failed to initialize

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#93]
https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/957/testReport/junit/(root)/projectroot/test_tlsf__rmw_connext_cpp/

```
[D0108|ENABLE]DDS_DomainParticipant_enableI:Automatic participant index failed to initialize. PLEASE VERIFY CONSISTENT TRANSPORT / DISCOVERY CONFIGURATION. 
DDSDomainParticipant_impl::createI:ERROR: Failed to auto-enable entity
```

[This post](https://community.rti.com/forum-topic/please-verify-constistent-transport-discovery-configuration?destination=node/3840) says it's from a network interface configuration issue.

Failed on repeat 12 and there have been CI jobs not showing this error since then so it seems like bad luck.

**Comment by dhood** [comment]
I asked on for details on the connext forum: https://community.rti.com/forum-topic/please-verify-constistent-transport-discovery-configuration

**Comment by dhood** [comment]
This is still an issue, though it has low probability. It can interfere with testing of flaky tests where we're repeating many times (e.g. it failed on repeat 417 in this flakiness-testing build: https://ci.ros2.org/job/ci_linux/4085).

The response on the forum was:


> The error that you are facing is due there is not interface up and running when the participant is created.
> So, there are two workarounds:
> 1. There is always an interface up and running on your system
> 2. It is possible to set the <participant_id> QoS manually. You can find more information in the “8.5.9 WIRE_PROTOCOL QosPolicy (DDS Extension)” section of the User’s Manual. 
Example:

```
<participant_qos>
    <wire_protocol>
        <participant_id>1</participant_id>
    </wire_protocol>
</participant_qos>
```

Setting the participant ID manually isn't really viable even if it's do-able for tests. This should be resolved for users that want automatic participant ID selection.

@ros2/team Is anyone aware of issues that would impact the interface availability in the docker containers? Is there something we can improve there, or -- given that the interface is fine for all other runs of the tests -- is this more likely an issue in how connext is working with the interface?

**Comment by dhood** [comment]
another test failure from this: https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/968/testReport/junit/(root)/projectroot/test_demo_cyclic_pipeline__rmw_connext_cpp/

**Comment by dhood** [comment]
I asked for specifics on what changed between connext versions but haven't heard back: https://community.rti.com/forum-topic/please-verify-constistent-transport-discovery-configuration

**Comment by dirk-thomas** [comment]
Since we haven't seen this for quite a while I will go ahead and close the ticket for now.
