### ISSUE TITLE
rtiddsgen crashes sporadically on windows

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#95]
A Windows job crashed last night on a message package:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/747/consoleFull
```
23:48:57          Creating "x64\Release\rcl_interfaces__dds_connext_idl\rcl_inte.8597C808.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
23:48:57        CustomBuild:
23:48:57          Building Custom Rule C:/J/workspace/nightly_win_rel/ws/src/ros2/rcl_interfaces/rcl_interfaces/CMakeLists.txt
23:48:58          CMake does not need to re-run because C:/J/workspace/nightly_win_rel/ws/build/rcl_interfaces/CMakeFiles/generate.stamp is up-to-date.
23:48:58          Generating DDS interfaces
23:48:58          Generating C++ type support for RTI Connext (using 'rtiddsgen_server.bat')
23:48:58   Duration_Support.cxx
23:48:58     27>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code -1073741819. 
```

This is suspected to be another instance of https://github.com/ros2/build_cop/issues/40, but it's not quite confirmed yet because one of the other parallel tasks could have also caused the build to crash.

We used to have to use a patched version of `rtiddsgen` on windows for 5.2.3 to avoid a crash when running in parallel, but we understood it was supposed to be fixed in 5.3.

**Comment by clalancette** [comment]
This hasn't popped up in https://ci.ros2.org/view/nightly/job/nightly_win_rel/ for over 3 weeks now.  I'm going to close this out; feel free to reopen if it occurs again.
