### ISSUE TITLE
Test weak nodes failing since Mar 13, 2018

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#96]
While it was flaky before, it looks that it got worse recently
Last night testWeakNodes failed on various platforms:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/751/
https://ci.ros2.org/view/nightly/job/nightly_win_deb/813/
https://ci.ros2.org/view/nightly/job/nightly_osx_release/783/
https://ci.ros2.org/view/nightly/job/nightly_osx_debug/785/

Only changes since yesterday that seem relevant is:
https://github.com/ros2/rclcpp/pull/431 (@wjwwood is it possible that this PR caused the failure?)

There was also a change inf Fast-RTPS but I don't think it's the cause:
https://github.com/eProsima/Fast-RTPS/commit/3514b098b70b2e9ccb3e044c8a10187a10e320e4

**Comment by clalancette** [comment]
Running it under valgrind showed me this: https://gist.github.com/clalancette/92c4a2a0a3c396b339e839ed5fe4753c

**Comment by wjwwood** [comment]
Ok, sorry guys I saw that test and thought it was flaky, but I guess I was too hasty. Let me revert that change and bring this regression to the contributors attention.
